# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eco_cont_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EcologicalContinuityDialogBase(object):
    def setupUi(self, EcologicalContinuityDialogBase):
        EcologicalContinuityDialogBase.setObjectName("EcologicalContinuityDialogBase")
        EcologicalContinuityDialogBase.resize(939, 663)
        self.groups = QtWidgets.QTabWidget(EcologicalContinuityDialogBase)
        self.groups.setGeometry(QtCore.QRect(40, 20, 841, 591))
        self.groups.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.groups.setObjectName("groups")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.paramlabel = QtWidgets.QLabel(self.tab_9)
        self.paramlabel.setGeometry(QtCore.QRect(40, 20, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel.setFont(font)
        self.paramlabel.setObjectName("paramlabel")
        self.frame_7 = QtWidgets.QFrame(self.tab_9)
        self.frame_7.setGeometry(QtCore.QRect(70, 420, 271, 111))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.paramlabel_3 = QtWidgets.QLabel(self.frame_7)
        self.paramlabel_3.setGeometry(QtCore.QRect(0, 0, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel_3.setFont(font)
        self.paramlabel_3.setObjectName("paramlabel_3")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label_23.setObjectName("label_23")
        self.loadModelPath = QgsFileWidget(self.frame_7)
        self.loadModelPath.setGeometry(QtCore.QRect(90, 50, 141, 27))
        self.loadModelPath.setObjectName("loadModelPath")
        self.loadModelButton = QtWidgets.QPushButton(self.frame_7)
        self.loadModelButton.setGeometry(QtCore.QRect(160, 80, 75, 23))
        self.loadModelButton.setObjectName("loadModelButton")
        self.checkBox = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox.setGeometry(QtCore.QRect(210, 30, 16, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label_22.setObjectName("label_22")
        self.frame_8 = QtWidgets.QFrame(self.tab_9)
        self.frame_8.setGeometry(QtCore.QRect(610, 340, 201, 211))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.paramlabel_4 = QtWidgets.QLabel(self.frame_8)
        self.paramlabel_4.setGeometry(QtCore.QRect(0, 0, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel_4.setFont(font)
        self.paramlabel_4.setObjectName("paramlabel_4")
        self.runGroupCB = QtWidgets.QCheckBox(self.frame_8)
        self.runGroupCB.setGeometry(QtCore.QRect(150, 30, 16, 17))
        self.runGroupCB.setText("")
        self.runGroupCB.setObjectName("runGroupCB")
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        self.label_24.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label_24.setObjectName("label_24")
        self.label_35 = QtWidgets.QLabel(self.frame_8)
        self.label_35.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label_35.setObjectName("label_35")
        self.runMetagroupCB = QtWidgets.QCheckBox(self.frame_8)
        self.runMetagroupCB.setGeometry(QtCore.QRect(150, 50, 16, 17))
        self.runMetagroupCB.setText("")
        self.runMetagroupCB.setObjectName("runMetagroupCB")
        self.label_36 = QtWidgets.QLabel(self.frame_8)
        self.label_36.setGeometry(QtCore.QRect(30, 70, 111, 16))
        self.label_36.setObjectName("label_36")
        self.runSelectionCB = QtWidgets.QCheckBox(self.frame_8)
        self.runSelectionCB.setGeometry(QtCore.QRect(150, 70, 16, 17))
        self.runSelectionCB.setText("")
        self.runSelectionCB.setObjectName("runSelectionCB")
        self.label_37 = QtWidgets.QLabel(self.frame_8)
        self.label_37.setGeometry(QtCore.QRect(30, 90, 111, 16))
        self.label_37.setObjectName("label_37")
        self.runTamponCB = QtWidgets.QCheckBox(self.frame_8)
        self.runTamponCB.setGeometry(QtCore.QRect(150, 90, 16, 17))
        self.runTamponCB.setText("")
        self.runTamponCB.setObjectName("runTamponCB")
        self.label_38 = QtWidgets.QLabel(self.frame_8)
        self.label_38.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.label_38.setObjectName("label_38")
        self.runRasterizationCB = QtWidgets.QCheckBox(self.frame_8)
        self.runRasterizationCB.setGeometry(QtCore.QRect(150, 110, 16, 17))
        self.runRasterizationCB.setText("")
        self.runRasterizationCB.setObjectName("runRasterizationCB")
        self.label_39 = QtWidgets.QLabel(self.frame_8)
        self.label_39.setGeometry(QtCore.QRect(30, 130, 111, 16))
        self.label_39.setObjectName("label_39")
        self.runFrictionCB = QtWidgets.QCheckBox(self.frame_8)
        self.runFrictionCB.setGeometry(QtCore.QRect(150, 130, 16, 17))
        self.runFrictionCB.setText("")
        self.runFrictionCB.setObjectName("runFrictionCB")
        self.label_40 = QtWidgets.QLabel(self.frame_8)
        self.label_40.setGeometry(QtCore.QRect(30, 150, 111, 16))
        self.label_40.setObjectName("label_40")
        self.runCostCB = QtWidgets.QCheckBox(self.frame_8)
        self.runCostCB.setGeometry(QtCore.QRect(150, 150, 16, 17))
        self.runCostCB.setText("")
        self.runCostCB.setObjectName("runCostCB")
        self.pushButton = QtWidgets.QPushButton(self.frame_8)
        self.pushButton.setGeometry(QtCore.QRect(90, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.frame_9 = QtWidgets.QFrame(self.tab_9)
        self.frame_9.setGeometry(QtCore.QRect(70, 330, 251, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.paramlabel_2 = QtWidgets.QLabel(self.frame_9)
        self.paramlabel_2.setGeometry(QtCore.QRect(0, 0, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel_2.setFont(font)
        self.paramlabel_2.setObjectName("paramlabel_2")
        self.saveModelPath = QgsFileWidget(self.frame_9)
        self.saveModelPath.setGeometry(QtCore.QRect(70, 30, 141, 27))
        self.saveModelPath.setObjectName("saveModelPath")
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        self.label_41.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_41.setObjectName("label_41")
        self.saveModelButton = QtWidgets.QPushButton(self.frame_9)
        self.saveModelButton.setGeometry(QtCore.QRect(130, 60, 75, 23))
        self.saveModelButton.setObjectName("saveModelButton")
        self.frame_12 = QtWidgets.QFrame(self.tab_9)
        self.frame_12.setGeometry(QtCore.QRect(70, 50, 381, 161))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.workspace = QgsFileWidget(self.frame_12)
        self.workspace.setGeometry(QtCore.QRect(110, 0, 151, 27))
        self.workspace.setObjectName("workspace")
        self.label_44 = QtWidgets.QLabel(self.frame_12)
        self.label_44.setGeometry(QtCore.QRect(0, 0, 111, 16))
        self.label_44.setObjectName("label_44")
        self.extentLayer = QgsFileWidget(self.frame_12)
        self.extentLayer.setGeometry(QtCore.QRect(110, 30, 151, 27))
        self.extentLayer.setObjectName("extentLayer")
        self.label_45 = QtWidgets.QLabel(self.frame_12)
        self.label_45.setGeometry(QtCore.QRect(1, 30, 111, 16))
        self.label_45.setObjectName("label_45")
        self.rasterResolution = QgsSpinBox(self.frame_12)
        self.rasterResolution.setGeometry(QtCore.QRect(110, 60, 151, 27))
        self.rasterResolution.setMaximum(999999)
        self.rasterResolution.setObjectName("rasterResolution")
        self.label_46 = QtWidgets.QLabel(self.frame_12)
        self.label_46.setGeometry(QtCore.QRect(1, 60, 111, 16))
        self.label_46.setObjectName("label_46")
        self.paramsRelPath = QtWidgets.QCheckBox(self.frame_12)
        self.paramsRelPath.setGeometry(QtCore.QRect(140, 110, 16, 17))
        self.paramsRelPath.setText("")
        self.paramsRelPath.setObjectName("paramsRelPath")
        self.paramsRelPath_3 = QtWidgets.QCheckBox(self.frame_12)
        self.paramsRelPath_3.setGeometry(QtCore.QRect(140, 130, 16, 17))
        self.paramsRelPath_3.setText("")
        self.paramsRelPath_3.setObjectName("paramsRelPath_3")
        self.label_48 = QtWidgets.QLabel(self.frame_12)
        self.label_48.setGeometry(QtCore.QRect(0, 110, 111, 16))
        self.label_48.setObjectName("label_48")
        self.label_107 = QtWidgets.QLabel(self.frame_12)
        self.label_107.setGeometry(QtCore.QRect(0, 130, 111, 16))
        self.label_107.setObjectName("label_107")
        self.groups.addTab(self.tab_9, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.frame_28 = QtWidgets.QFrame(self.tab_19)
        self.frame_28.setGeometry(QtCore.QRect(20, 10, 381, 361))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.stView = QtWidgets.QTableView(self.frame_28)
        self.stView.setGeometry(QtCore.QRect(10, 110, 361, 241))
        self.stView.setObjectName("stView")
        self.label_102 = QtWidgets.QLabel(self.frame_28)
        self.label_102.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.stFilter = QtWidgets.QLineEdit(self.frame_28)
        self.stFilter.setGeometry(QtCore.QRect(20, 80, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stFilter.setFont(font)
        self.stFilter.setObjectName("stFilter")
        self.stRemove = QtWidgets.QPushButton(self.frame_28)
        self.stRemove.setGeometry(QtCore.QRect(170, 80, 75, 23))
        self.stRemove.setObjectName("stRemove")
        self.stAdd = QtWidgets.QPushButton(self.frame_28)
        self.stAdd.setGeometry(QtCore.QRect(280, 80, 75, 23))
        self.stAdd.setObjectName("stAdd")
        self.stDescr = QtWidgets.QLineEdit(self.frame_28)
        self.stDescr.setGeometry(QtCore.QRect(120, 50, 231, 20))
        self.stDescr.setObjectName("stDescr")
        self.stName = QtWidgets.QLineEdit(self.frame_28)
        self.stName.setGeometry(QtCore.QRect(120, 20, 231, 20))
        self.stName.setObjectName("stName")
        self.label_103 = QtWidgets.QLabel(self.frame_28)
        self.label_103.setGeometry(QtCore.QRect(40, 20, 47, 13))
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.frame_28)
        self.label_104.setGeometry(QtCore.QRect(40, 50, 61, 16))
        self.label_104.setObjectName("label_104")
        self.frame_2 = QtWidgets.QFrame(self.tab_19)
        self.frame_2.setGeometry(QtCore.QRect(420, 10, 381, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_111 = QtWidgets.QLabel(self.frame_2)
        self.label_111.setGeometry(QtCore.QRect(0, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.groupsAdd = QtWidgets.QPushButton(self.frame_2)
        self.groupsAdd.setGeometry(QtCore.QRect(250, 80, 75, 23))
        self.groupsAdd.setObjectName("groupsAdd")
        self.label_108 = QtWidgets.QLabel(self.frame_2)
        self.label_108.setGeometry(QtCore.QRect(30, 50, 61, 16))
        self.label_108.setObjectName("label_108")
        self.label_109 = QtWidgets.QLabel(self.frame_2)
        self.label_109.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_109.setObjectName("label_109")
        self.groupsRemove = QtWidgets.QPushButton(self.frame_2)
        self.groupsRemove.setGeometry(QtCore.QRect(170, 80, 75, 23))
        self.groupsRemove.setObjectName("groupsRemove")
        self.groupsName = QtWidgets.QLineEdit(self.frame_2)
        self.groupsName.setGeometry(QtCore.QRect(100, 20, 231, 20))
        self.groupsName.setObjectName("groupsName")
        self.groupsDescr = QtWidgets.QLineEdit(self.frame_2)
        self.groupsDescr.setGeometry(QtCore.QRect(100, 50, 231, 20))
        self.groupsDescr.setObjectName("groupsDescr")
        self.groupsView = QtWidgets.QTableView(self.frame_2)
        self.groupsView.setGeometry(QtCore.QRect(10, 110, 361, 241))
        self.groupsView.setObjectName("groupsView")
        self.groups.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.frame_29 = QtWidgets.QFrame(self.tab_20)
        self.frame_29.setGeometry(QtCore.QRect(10, 10, 821, 541))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.selectionView = QtWidgets.QTableView(self.frame_29)
        self.selectionView.setGeometry(QtCore.QRect(20, 310, 751, 192))
        self.selectionView.setObjectName("selectionView")
        self.selectionRun = QtWidgets.QPushButton(self.frame_29)
        self.selectionRun.setGeometry(QtCore.QRect(360, 510, 75, 23))
        self.selectionRun.setObjectName("selectionRun")
        self.selectionRemove = QtWidgets.QPushButton(self.frame_29)
        self.selectionRemove.setGeometry(QtCore.QRect(160, 280, 75, 23))
        self.selectionRemove.setObjectName("selectionRemove")
        self.selectionFilter = QtWidgets.QLineEdit(self.frame_29)
        self.selectionFilter.setGeometry(QtCore.QRect(20, 280, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectionFilter.setFont(font)
        self.selectionFilter.setObjectName("selectionFilter")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setGeometry(QtCore.QRect(10, 0, 451, 261))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.selectionGroupCombo = QtWidgets.QComboBox(self.frame_30)
        self.selectionGroupCombo.setGeometry(QtCore.QRect(80, 170, 121, 22))
        self.selectionGroupCombo.setObjectName("selectionGroupCombo")
        self.selectionExpr = QgsFieldExpressionWidget(self.frame_30)
        self.selectionExpr.setGeometry(QtCore.QRect(160, 120, 281, 21))
        self.selectionExpr.setObjectName("selectionExpr")
        self.selectionGroupLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionGroupLabel.setGeometry(QtCore.QRect(10, 170, 61, 21))
        self.selectionGroupLabel.setObjectName("selectionGroupLabel")
        self.selectionGroupName = QtWidgets.QLineEdit(self.frame_30)
        self.selectionGroupName.setGeometry(QtCore.QRect(210, 170, 91, 20))
        self.selectionGroupName.setObjectName("selectionGroupName")
        self.selectionExprLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionExprLabel.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.selectionExprLabel.setObjectName("selectionExprLabel")
        self.selectionInLayer = QgsFileWidget(self.frame_30)
        self.selectionInLayer.setGeometry(QtCore.QRect(270, 50, 171, 27))
        self.selectionInLayer.setObjectName("selectionInLayer")
        self.selectionLayerLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionLayerLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.selectionLayerLabel.setObjectName("selectionLayerLabel")
        self.selectionInLayerCombo = QgsMapLayerComboBox(self.frame_30)
        self.selectionInLayerCombo.setGeometry(QtCore.QRect(80, 50, 171, 21))
        self.selectionInLayerCombo.setObjectName("selectionInLayerCombo")
        self.selectionAdd = QtWidgets.QPushButton(self.frame_30)
        self.selectionAdd.setGeometry(QtCore.QRect(314, 230, 121, 23))
        self.selectionAdd.setObjectName("selectionAdd")
        self.selectionClassLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionClassLabel.setGeometry(QtCore.QRect(10, 200, 61, 21))
        self.selectionClassLabel.setObjectName("selectionClassLabel")
        self.selectionClassDescr = QtWidgets.QLineEdit(self.frame_30)
        self.selectionClassDescr.setGeometry(QtCore.QRect(310, 200, 131, 20))
        self.selectionClassDescr.setObjectName("selectionClassDescr")
        self.selectionClassCombo = QtWidgets.QComboBox(self.frame_30)
        self.selectionClassCombo.setGeometry(QtCore.QRect(80, 200, 121, 22))
        self.selectionClassCombo.setObjectName("selectionClassCombo")
        self.selectionFieldLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionFieldLabel.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.selectionFieldLabel.setObjectName("selectionFieldLabel")
        self.selectionField = QgsFieldComboBox(self.frame_30)
        self.selectionField.setGeometry(QtCore.QRect(160, 120, 281, 21))
        self.selectionField.setObjectName("selectionField")
        self.selectionClassName = QtWidgets.QLineEdit(self.frame_30)
        self.selectionClassName.setGeometry(QtCore.QRect(210, 200, 91, 20))
        self.selectionClassName.setObjectName("selectionClassName")
        self.selectionGroupDescr = QtWidgets.QLineEdit(self.frame_30)
        self.selectionGroupDescr.setGeometry(QtCore.QRect(310, 170, 131, 20))
        self.selectionGroupDescr.setObjectName("selectionGroupDescr")
        self.selectionLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionLabel.setGeometry(QtCore.QRect(190, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selectionLabel.setFont(font)
        self.selectionLabel.setObjectName("selectionLabel")
        self.fieldSelectionMode = QtWidgets.QCheckBox(self.frame_30)
        self.fieldSelectionMode.setGeometry(QtCore.QRect(160, 100, 70, 17))
        self.fieldSelectionMode.setObjectName("fieldSelectionMode")
        self.selectionModeLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionModeLabel.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.selectionModeLabel.setObjectName("selectionModeLabel")
        self.exprSelectionMode = QtWidgets.QCheckBox(self.frame_30)
        self.exprSelectionMode.setGeometry(QtCore.QRect(290, 100, 101, 17))
        self.exprSelectionMode.setObjectName("exprSelectionMode")
        self.classView = QtWidgets.QTableView(self.frame_29)
        self.classView.setGeometry(QtCore.QRect(470, 40, 301, 241))
        self.classView.setObjectName("classView")
        self.classesLabel = QtWidgets.QLabel(self.frame_29)
        self.classesLabel.setGeometry(QtCore.QRect(600, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.classesLabel.setFont(font)
        self.classesLabel.setObjectName("classesLabel")
        self.groups.addTab(self.tab_20, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.frame_11 = QtWidgets.QFrame(self.tab_6)
        self.frame_11.setGeometry(QtCore.QRect(20, 10, 421, 501))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.fusionRemove = QtWidgets.QPushButton(self.frame_11)
        self.fusionRemove.setGeometry(QtCore.QRect(230, 150, 51, 23))
        self.fusionRemove.setObjectName("fusionRemove")
        self.fusionAdd = QtWidgets.QPushButton(self.frame_11)
        self.fusionAdd.setGeometry(QtCore.QRect(270, 110, 51, 23))
        self.fusionAdd.setObjectName("fusionAdd")
        self.bufferInGroupLabel_3 = QtWidgets.QLabel(self.frame_11)
        self.bufferInGroupLabel_3.setGeometry(QtCore.QRect(12, 40, 81, 21))
        self.bufferInGroupLabel_3.setObjectName("bufferInGroupLabel_3")
        self.fusionST = QtWidgets.QComboBox(self.frame_11)
        self.fusionST.setGeometry(QtCore.QRect(120, 40, 201, 22))
        self.fusionST.setObjectName("fusionST")
        self.label_27 = QtWidgets.QLabel(self.frame_11)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.fusionUp = QtWidgets.QPushButton(self.frame_11)
        self.fusionUp.setGeometry(QtCore.QRect(10, 182, 41, 31))
        self.fusionUp.setText("")
        self.fusionUp.setObjectName("fusionUp")
        self.fusionDown = QtWidgets.QPushButton(self.frame_11)
        self.fusionDown.setGeometry(QtCore.QRect(10, 220, 41, 31))
        self.fusionDown.setText("")
        self.fusionDown.setObjectName("fusionDown")
        self.fusionGroup = QtWidgets.QComboBox(self.frame_11)
        self.fusionGroup.setGeometry(QtCore.QRect(120, 110, 141, 22))
        self.fusionGroup.setObjectName("fusionGroup")
        self.bufferInGroupLabel_5 = QtWidgets.QLabel(self.frame_11)
        self.bufferInGroupLabel_5.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.bufferInGroupLabel_5.setObjectName("bufferInGroupLabel_5")
        self.bufferInGroupLabel_6 = QtWidgets.QLabel(self.frame_11)
        self.bufferInGroupLabel_6.setGeometry(QtCore.QRect(10, 70, 131, 21))
        self.bufferInGroupLabel_6.setObjectName("bufferInGroupLabel_6")
        self.fusionLoadGroups = QtWidgets.QPushButton(self.frame_11)
        self.fusionLoadGroups.setGeometry(QtCore.QRect(230, 70, 91, 23))
        self.fusionLoadGroups.setObjectName("fusionLoadGroups")
        self.fusionView = QtWidgets.QTableView(self.frame_11)
        self.fusionView.setGeometry(QtCore.QRect(60, 180, 256, 192))
        self.fusionView.setObjectName("fusionView")
        self.fusionRunAll = QtWidgets.QPushButton(self.frame_11)
        self.fusionRunAll.setGeometry(QtCore.QRect(150, 380, 61, 31))
        self.fusionRunAll.setObjectName("fusionRunAll")
        self.fusionRun = QtWidgets.QPushButton(self.frame_11)
        self.fusionRun.setGeometry(QtCore.QRect(264, 380, 51, 31))
        self.fusionRun.setObjectName("fusionRun")
        self.groups.addTab(self.tab_6, "")
        self.Friction = QtWidgets.QWidget()
        self.Friction.setObjectName("Friction")
        self.frame_10 = QtWidgets.QFrame(self.Friction)
        self.frame_10.setGeometry(QtCore.QRect(20, 20, 421, 421))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frictionView = QtWidgets.QTableView(self.frame_10)
        self.frictionView.setGeometry(QtCore.QRect(10, 70, 321, 191))
        self.frictionView.setObjectName("frictionView")
        self.bufferRemove_2 = QtWidgets.QPushButton(self.frame_10)
        self.bufferRemove_2.setGeometry(QtCore.QRect(150, 40, 75, 23))
        self.bufferRemove_2.setObjectName("bufferRemove_2")
        self.frictionRun = QtWidgets.QPushButton(self.frame_10)
        self.frictionRun.setGeometry(QtCore.QRect(250, 270, 75, 23))
        self.frictionRun.setObjectName("frictionRun")
        self.selectionFilter_4 = QtWidgets.QLineEdit(self.frame_10)
        self.selectionFilter_4.setGeometry(QtCore.QRect(10, 40, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectionFilter_4.setFont(font)
        self.selectionFilter_4.setObjectName("selectionFilter_4")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.frictionCsvFile = QgsFileWidget(self.frame_10)
        self.frictionCsvFile.setGeometry(QtCore.QRect(40, 320, 211, 27))
        self.frictionCsvFile.setObjectName("frictionCsvFile")
        self.frictionSave = QtWidgets.QPushButton(self.frame_10)
        self.frictionSave.setGeometry(QtCore.QRect(260, 320, 75, 23))
        self.frictionSave.setObjectName("frictionSave")
        self.mExtentGroupBox = QgsExtentGroupBox(self.Friction)
        self.mExtentGroupBox.setGeometry(QtCore.QRect(510, 70, 300, 139))
        self.mExtentGroupBox.setObjectName("mExtentGroupBox")
        self.groups.addTab(self.Friction, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 20, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(100, 110, 46, 13))
        self.label_3.setObjectName("label_3")
        self.costStartRaster = QgsMapLayerComboBox(self.tab)
        self.costStartRaster.setGeometry(QtCore.QRect(220, 20, 160, 27))
        self.costStartRaster.setObjectName("costStartRaster")
        self.costPermRaster = QgsMapLayerComboBox(self.tab)
        self.costPermRaster.setGeometry(QtCore.QRect(220, 60, 160, 27))
        self.costPermRaster.setObjectName("costPermRaster")
        self.costMaxVal = QgsSpinBox(self.tab)
        self.costMaxVal.setGeometry(QtCore.QRect(250, 110, 90, 27))
        self.costMaxVal.setObjectName("costMaxVal")
        self.runButton = QtWidgets.QPushButton(self.tab)
        self.runButton.setGeometry(QtCore.QRect(310, 490, 75, 23))
        self.runButton.setObjectName("runButton")
        self.costOutLayer = QgsFileWidget(self.tab)
        self.costOutLayer.setGeometry(QtCore.QRect(220, 150, 171, 21))
        self.costOutLayer.setObjectName("costOutLayer")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(80, 150, 91, 16))
        self.label_29.setObjectName("label_29")
        self.rasterView_2 = QtWidgets.QTableView(self.tab)
        self.rasterView_2.setGeometry(QtCore.QRect(80, 280, 321, 191))
        self.rasterView_2.setObjectName("rasterView_2")
        self.costRemove = QtWidgets.QPushButton(self.tab)
        self.costRemove.setGeometry(QtCore.QRect(310, 220, 75, 23))
        self.costRemove.setObjectName("costRemove")
        self.costAdd = QtWidgets.QPushButton(self.tab)
        self.costAdd.setGeometry(QtCore.QRect(230, 220, 75, 23))
        self.costAdd.setObjectName("costAdd")
        self.groups.addTab(self.tab, "")

        self.retranslateUi(EcologicalContinuityDialogBase)
        self.groups.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(EcologicalContinuityDialogBase)

    def retranslateUi(self, EcologicalContinuityDialogBase):
        _translate = QtCore.QCoreApplication.translate
        EcologicalContinuityDialogBase.setWindowTitle(_translate("EcologicalContinuityDialogBase", "Plugin Test"))
        self.paramlabel.setText(_translate("EcologicalContinuityDialogBase", "Paramètres"))
        self.paramlabel_3.setText(_translate("EcologicalContinuityDialogBase", "Charger"))
        self.label_23.setText(_translate("EcologicalContinuityDialogBase", "Model path"))
        self.loadModelButton.setText(_translate("EcologicalContinuityDialogBase", "Load"))
        self.label_22.setText(_translate("EcologicalContinuityDialogBase", "Erase current model"))
        self.paramlabel_4.setText(_translate("EcologicalContinuityDialogBase", "Lancer traitements"))
        self.label_24.setText(_translate("EcologicalContinuityDialogBase", "Groups"))
        self.label_35.setText(_translate("EcologicalContinuityDialogBase", "Metagroups"))
        self.label_36.setText(_translate("EcologicalContinuityDialogBase", "Sélection"))
        self.label_37.setText(_translate("EcologicalContinuityDialogBase", "Tampons"))
        self.label_38.setText(_translate("EcologicalContinuityDialogBase", "Rasterization"))
        self.label_39.setText(_translate("EcologicalContinuityDialogBase", "Friction"))
        self.label_40.setText(_translate("EcologicalContinuityDialogBase", "Coût cumulé"))
        self.pushButton.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.paramlabel_2.setText(_translate("EcologicalContinuityDialogBase", "Sauvegarder"))
        self.label_41.setText(_translate("EcologicalContinuityDialogBase", "Model path"))
        self.saveModelButton.setText(_translate("EcologicalContinuityDialogBase", "Save"))
        self.label_44.setText(_translate("EcologicalContinuityDialogBase", "Dossier de travail*"))
        self.label_45.setText(_translate("EcologicalContinuityDialogBase", "Couche d\'emprise*"))
        self.label_46.setText(_translate("EcologicalContinuityDialogBase", "Résolution raster*"))
        self.label_48.setText(_translate("EcologicalContinuityDialogBase", "Use relative paths"))
        self.label_107.setText(_translate("EcologicalContinuityDialogBase", "Override existing files"))
        self.groups.setTabText(self.groups.indexOf(self.tab_9), _translate("EcologicalContinuityDialogBase", "MainPanel"))
        self.label_102.setText(_translate("EcologicalContinuityDialogBase", "Sous-trames"))
        self.stFilter.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[Filter]"))
        self.stRemove.setText(_translate("EcologicalContinuityDialogBase", "Remove"))
        self.stAdd.setText(_translate("EcologicalContinuityDialogBase", "Add"))
        self.label_103.setText(_translate("EcologicalContinuityDialogBase", "Name"))
        self.label_104.setText(_translate("EcologicalContinuityDialogBase", "Description"))
        self.label_111.setText(_translate("EcologicalContinuityDialogBase", "Groupes"))
        self.groupsAdd.setText(_translate("EcologicalContinuityDialogBase", "Add"))
        self.label_108.setText(_translate("EcologicalContinuityDialogBase", "Description"))
        self.label_109.setText(_translate("EcologicalContinuityDialogBase", "Name"))
        self.groupsRemove.setText(_translate("EcologicalContinuityDialogBase", "Remove"))
        self.groups.setTabText(self.groups.indexOf(self.tab_19), _translate("EcologicalContinuityDialogBase", "Classes"))
        self.selectionRun.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.selectionRemove.setText(_translate("EcologicalContinuityDialogBase", "Remove"))
        self.selectionFilter.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[Filter]"))
        self.selectionGroupLabel.setText(_translate("EcologicalContinuityDialogBase", "Groupe"))
        self.selectionGroupName.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[name]"))
        self.selectionExprLabel.setText(_translate("EcologicalContinuityDialogBase", "Expression"))
        self.selectionLayerLabel.setText(_translate("EcologicalContinuityDialogBase", "Couche"))
        self.selectionAdd.setText(_translate("EcologicalContinuityDialogBase", "Add Selection"))
        self.selectionClassLabel.setText(_translate("EcologicalContinuityDialogBase", "Classe"))
        self.selectionClassDescr.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[description]"))
        self.selectionFieldLabel.setText(_translate("EcologicalContinuityDialogBase", "Champ"))
        self.selectionClassName.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[name]"))
        self.selectionGroupDescr.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[description]"))
        self.selectionLabel.setText(_translate("EcologicalContinuityDialogBase", "Sélection"))
        self.fieldSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Par champ"))
        self.selectionModeLabel.setText(_translate("EcologicalContinuityDialogBase", "Mode de sélection"))
        self.exprSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Par expression"))
        self.classesLabel.setText(_translate("EcologicalContinuityDialogBase", "Classes"))
        self.groups.setTabText(self.groups.indexOf(self.tab_20), _translate("EcologicalContinuityDialogBase", "Selection"))
        self.fusionRemove.setText(_translate("EcologicalContinuityDialogBase", "Remove"))
        self.fusionAdd.setText(_translate("EcologicalContinuityDialogBase", "Add"))
        self.bufferInGroupLabel_3.setText(_translate("EcologicalContinuityDialogBase", "Sous-trame"))
        self.label_27.setText(_translate("EcologicalContinuityDialogBase", "Fusion"))
        self.bufferInGroupLabel_5.setText(_translate("EcologicalContinuityDialogBase", "Groupe"))
        self.bufferInGroupLabel_6.setText(_translate("EcologicalContinuityDialogBase", "Charger tous les groupes"))
        self.fusionLoadGroups.setText(_translate("EcologicalContinuityDialogBase", "Load"))
        self.fusionRunAll.setText(_translate("EcologicalContinuityDialogBase", "Run All"))
        self.fusionRun.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.groups.setTabText(self.groups.indexOf(self.tab_6), _translate("EcologicalContinuityDialogBase", "5 - Fusion"))
        self.bufferRemove_2.setText(_translate("EcologicalContinuityDialogBase", "Remove"))
        self.frictionRun.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.selectionFilter_4.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[Filter]"))
        self.label_26.setText(_translate("EcologicalContinuityDialogBase", "Friction"))
        self.frictionSave.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.groups.setTabText(self.groups.indexOf(self.Friction), _translate("EcologicalContinuityDialogBase", "6 - Friction"))
        self.label.setText(_translate("EcologicalContinuityDialogBase", "Raster de départ"))
        self.label_2.setText(_translate("EcologicalContinuityDialogBase", "Raster de perméabilité"))
        self.label_3.setText(_translate("EcologicalContinuityDialogBase", "Coût max"))
        self.runButton.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.label_29.setText(_translate("EcologicalContinuityDialogBase", "Couche de sortie"))
        self.costRemove.setText(_translate("EcologicalContinuityDialogBase", "Remove"))
        self.costAdd.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.groups.setTabText(self.groups.indexOf(self.tab), _translate("EcologicalContinuityDialogBase", "7 - Coût cumulé"))

from qgis.gui import QgsExtentGroupBox, QgsFieldComboBox, QgsFieldExpressionWidget, QgsFileWidget, QgsMapLayerComboBox, QgsSpinBox
