# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eco_cont_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EcologicalContinuityDialogBase(object):
    def setupUi(self, EcologicalContinuityDialogBase):
        EcologicalContinuityDialogBase.setObjectName("EcologicalContinuityDialogBase")
        EcologicalContinuityDialogBase.resize(939, 780)
        self.pluginTabs = QtWidgets.QTabWidget(EcologicalContinuityDialogBase)
        self.pluginTabs.setGeometry(QtCore.QRect(40, 20, 871, 731))
        self.pluginTabs.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pluginTabs.setObjectName("pluginTabs")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.paramlabel = QtWidgets.QLabel(self.mainTab)
        self.paramlabel.setGeometry(QtCore.QRect(40, 20, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel.setFont(font)
        self.paramlabel.setObjectName("paramlabel")
        self.frame_9 = QtWidgets.QFrame(self.mainTab)
        self.frame_9.setGeometry(QtCore.QRect(40, 380, 361, 131))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.saveModelPath = QgsFileWidget(self.frame_9)
        self.saveModelPath.setGeometry(QtCore.QRect(160, 50, 171, 27))
        self.saveModelPath.setObjectName("saveModelPath")
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        self.label_41.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label_41.setObjectName("label_41")
        self.paramlabel_5 = QtWidgets.QLabel(self.frame_9)
        self.paramlabel_5.setGeometry(QtCore.QRect(0, 0, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel_5.setFont(font)
        self.paramlabel_5.setObjectName("paramlabel_5")
        self.loadModelPath = QgsFileWidget(self.frame_9)
        self.loadModelPath.setGeometry(QtCore.QRect(160, 20, 171, 27))
        self.loadModelPath.setObjectName("loadModelPath")
        self.label_29 = QtWidgets.QLabel(self.frame_9)
        self.label_29.setGeometry(QtCore.QRect(30, 20, 111, 16))
        self.label_29.setObjectName("label_29")
        self.label_42 = QtWidgets.QLabel(self.frame_9)
        self.label_42.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.label_42.setObjectName("label_42")
        self.saveProjectButton = QtWidgets.QPushButton(self.frame_9)
        self.saveProjectButton.setGeometry(QtCore.QRect(160, 80, 75, 23))
        self.saveProjectButton.setObjectName("saveProjectButton")
        self.frame_12 = QtWidgets.QFrame(self.mainTab)
        self.frame_12.setGeometry(QtCore.QRect(70, 50, 461, 121))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.workspace = QgsFileWidget(self.frame_12)
        self.workspace.setGeometry(QtCore.QRect(110, 0, 261, 21))
        self.workspace.setObjectName("workspace")
        self.label_44 = QtWidgets.QLabel(self.frame_12)
        self.label_44.setGeometry(QtCore.QRect(0, 0, 111, 16))
        self.label_44.setObjectName("label_44")
        self.extentLayer = QgsFileWidget(self.frame_12)
        self.extentLayer.setGeometry(QtCore.QRect(110, 30, 261, 21))
        self.extentLayer.setObjectName("extentLayer")
        self.label_45 = QtWidgets.QLabel(self.frame_12)
        self.label_45.setGeometry(QtCore.QRect(1, 30, 111, 16))
        self.label_45.setObjectName("label_45")
        self.rasterResolution = QgsSpinBox(self.frame_12)
        self.rasterResolution.setGeometry(QtCore.QRect(110, 60, 261, 21))
        self.rasterResolution.setMaximum(999999)
        self.rasterResolution.setObjectName("rasterResolution")
        self.label_46 = QtWidgets.QLabel(self.frame_12)
        self.label_46.setGeometry(QtCore.QRect(1, 60, 111, 16))
        self.label_46.setObjectName("label_46")
        self.paramsCrs = QgsProjectionSelectionWidget(self.frame_12)
        self.paramsCrs.setGeometry(QtCore.QRect(110, 90, 261, 21))
        self.paramsCrs.setObjectName("paramsCrs")
        self.label_47 = QtWidgets.QLabel(self.frame_12)
        self.label_47.setGeometry(QtCore.QRect(0, 90, 111, 16))
        self.label_47.setObjectName("label_47")
        self.paramsView = QtWidgets.QTableView(self.mainTab)
        self.paramsView.setGeometry(QtCore.QRect(40, 180, 511, 181))
        self.paramsView.setObjectName("paramsView")
        self.mExtentGroupBox = QgsExtentGroupBox(self.mainTab)
        self.mExtentGroupBox.setGeometry(QtCore.QRect(540, 40, 300, 139))
        self.mExtentGroupBox.setObjectName("mExtentGroupBox")
        self.pluginTabs.addTab(self.mainTab, "")
        self.stTab = QtWidgets.QWidget()
        self.stTab.setObjectName("stTab")
        self.frame_28 = QtWidgets.QFrame(self.stTab)
        self.frame_28.setGeometry(QtCore.QRect(30, 20, 441, 401))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.stView = QtWidgets.QTableView(self.frame_28)
        self.stView.setGeometry(QtCore.QRect(10, 110, 401, 271))
        self.stView.setObjectName("stView")
        self.label_102 = QtWidgets.QLabel(self.frame_28)
        self.label_102.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.stFilter = QtWidgets.QLineEdit(self.frame_28)
        self.stFilter.setGeometry(QtCore.QRect(20, 80, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stFilter.setFont(font)
        self.stFilter.setObjectName("stFilter")
        self.stRemove = QtWidgets.QPushButton(self.frame_28)
        self.stRemove.setGeometry(QtCore.QRect(190, 80, 211, 23))
        self.stRemove.setObjectName("stRemove")
        self.stAdd = QtWidgets.QPushButton(self.frame_28)
        self.stAdd.setGeometry(QtCore.QRect(40, 80, 111, 23))
        self.stAdd.setObjectName("stAdd")
        self.stDescr = QtWidgets.QLineEdit(self.frame_28)
        self.stDescr.setGeometry(QtCore.QRect(120, 50, 281, 20))
        self.stDescr.setObjectName("stDescr")
        self.stName = QtWidgets.QLineEdit(self.frame_28)
        self.stName.setGeometry(QtCore.QRect(120, 20, 281, 20))
        self.stName.setObjectName("stName")
        self.label_103 = QtWidgets.QLabel(self.frame_28)
        self.label_103.setGeometry(QtCore.QRect(40, 20, 47, 13))
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.frame_28)
        self.label_104.setGeometry(QtCore.QRect(40, 50, 61, 16))
        self.label_104.setObjectName("label_104")
        self.pluginTabs.addTab(self.stTab, "")
        self.selectionTab = QtWidgets.QWidget()
        self.selectionTab.setObjectName("selectionTab")
        self.frame_29 = QtWidgets.QFrame(self.selectionTab)
        self.frame_29.setGeometry(QtCore.QRect(10, 10, 841, 691))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.selectionView = QtWidgets.QTableView(self.frame_29)
        self.selectionView.setGeometry(QtCore.QRect(60, 401, 761, 221))
        self.selectionView.setObjectName("selectionView")
        self.selectionRun = QtWidgets.QPushButton(self.frame_29)
        self.selectionRun.setGeometry(QtCore.QRect(360, 650, 131, 31))
        self.selectionRun.setObjectName("selectionRun")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setGeometry(QtCore.QRect(10, 10, 441, 371))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.selectionAdd = QtWidgets.QPushButton(self.frame_30)
        self.selectionAdd.setGeometry(QtCore.QRect(160, 330, 121, 23))
        self.selectionAdd.setObjectName("selectionAdd")
        self.selectionLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionLabel.setGeometry(QtCore.QRect(30, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selectionLabel.setFont(font)
        self.selectionLabel.setObjectName("selectionLabel")
        self.frame_3 = QtWidgets.QFrame(self.frame_30)
        self.frame_3.setGeometry(QtCore.QRect(0, 140, 441, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.exprSelectionMode = QtWidgets.QCheckBox(self.frame_3)
        self.exprSelectionMode.setGeometry(QtCore.QRect(300, 20, 101, 17))
        self.exprSelectionMode.setObjectName("exprSelectionMode")
        self.selectionField = QgsFieldComboBox(self.frame_3)
        self.selectionField.setGeometry(QtCore.QRect(160, 40, 271, 21))
        self.selectionField.setObjectName("selectionField")
        self.selectionStep2Label = QtWidgets.QLabel(self.frame_3)
        self.selectionStep2Label.setGeometry(QtCore.QRect(0, 0, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionStep2Label.setFont(font)
        self.selectionStep2Label.setObjectName("selectionStep2Label")
        self.selectionExprLabel = QtWidgets.QLabel(self.frame_3)
        self.selectionExprLabel.setGeometry(QtCore.QRect(20, 40, 61, 21))
        self.selectionExprLabel.setObjectName("selectionExprLabel")
        self.selectionModeLabel = QtWidgets.QLabel(self.frame_3)
        self.selectionModeLabel.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.selectionModeLabel.setObjectName("selectionModeLabel")
        self.fieldSelectionMode = QtWidgets.QCheckBox(self.frame_3)
        self.fieldSelectionMode.setGeometry(QtCore.QRect(170, 20, 70, 17))
        self.fieldSelectionMode.setObjectName("fieldSelectionMode")
        self.selectionExpr = QgsFieldExpressionWidget(self.frame_3)
        self.selectionExpr.setGeometry(QtCore.QRect(160, 40, 271, 21))
        self.selectionExpr.setObjectName("selectionExpr")
        self.selectionFieldLabel = QtWidgets.QLabel(self.frame_3)
        self.selectionFieldLabel.setGeometry(QtCore.QRect(20, 40, 61, 21))
        self.selectionFieldLabel.setObjectName("selectionFieldLabel")
        self.selectionResampleLabel = QtWidgets.QLabel(self.frame_3)
        self.selectionResampleLabel.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.selectionResampleLabel.setObjectName("selectionResampleLabel")
        self.selectionResampleCombo = QtWidgets.QComboBox(self.frame_3)
        self.selectionResampleCombo.setGeometry(QtCore.QRect(160, 20, 271, 21))
        self.selectionResampleCombo.setObjectName("selectionResampleCombo")
        self.frame_4 = QtWidgets.QFrame(self.frame_30)
        self.frame_4.setGeometry(QtCore.QRect(0, 40, 441, 81))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.selectionInLayerCombo = QgsMapLayerComboBox(self.frame_4)
        self.selectionInLayerCombo.setGeometry(QtCore.QRect(150, 40, 281, 16))
        self.selectionInLayerCombo.setObjectName("selectionInLayerCombo")
        self.selectionExprLabel_3 = QtWidgets.QLabel(self.frame_4)
        self.selectionExprLabel_3.setGeometry(QtCore.QRect(20, 60, 101, 21))
        self.selectionExprLabel_3.setObjectName("selectionExprLabel_3")
        self.selectionInLayer = QgsFileWidget(self.frame_4)
        self.selectionInLayer.setGeometry(QtCore.QRect(150, 60, 281, 16))
        self.selectionInLayer.setObjectName("selectionInLayer")
        self.selectionLayerLabel = QtWidgets.QLabel(self.frame_4)
        self.selectionLayerLabel.setGeometry(QtCore.QRect(0, 0, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionLayerLabel.setFont(font)
        self.selectionLayerLabel.setObjectName("selectionLayerLabel")
        self.selectionExprLabel_2 = QtWidgets.QLabel(self.frame_4)
        self.selectionExprLabel_2.setGeometry(QtCore.QRect(20, 40, 101, 21))
        self.selectionExprLabel_2.setObjectName("selectionExprLabel_2")
        self.selectionLayerFormatLabel = QtWidgets.QLabel(self.frame_4)
        self.selectionLayerFormatLabel.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.selectionLayerFormatLabel.setObjectName("selectionLayerFormatLabel")
        self.selectionLayerFormatVector = QtWidgets.QCheckBox(self.frame_4)
        self.selectionLayerFormatVector.setGeometry(QtCore.QRect(180, 20, 70, 17))
        self.selectionLayerFormatVector.setObjectName("selectionLayerFormatVector")
        self.selectionLayerFormatRaster = QtWidgets.QCheckBox(self.frame_4)
        self.selectionLayerFormatRaster.setGeometry(QtCore.QRect(300, 20, 70, 17))
        self.selectionLayerFormatRaster.setObjectName("selectionLayerFormatRaster")
        self.frame_5 = QtWidgets.QFrame(self.frame_30)
        self.frame_5.setGeometry(QtCore.QRect(0, 230, 441, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.groupDisplay = QtWidgets.QCheckBox(self.frame_5)
        self.groupDisplay.setGeometry(QtCore.QRect(180, 0, 101, 17))
        self.groupDisplay.setObjectName("groupDisplay")
        self.selectionGroupLabel = QtWidgets.QLabel(self.frame_5)
        self.selectionGroupLabel.setGeometry(QtCore.QRect(0, 0, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionGroupLabel.setFont(font)
        self.selectionGroupLabel.setObjectName("selectionGroupLabel")
        self.selectionGroupAdd = QtWidgets.QPushButton(self.frame_5)
        self.selectionGroupAdd.setGeometry(QtCore.QRect(380, 50, 51, 23))
        self.selectionGroupAdd.setObjectName("selectionGroupAdd")
        self.selectionGroupCombo = QtWidgets.QComboBox(self.frame_5)
        self.selectionGroupCombo.setGeometry(QtCore.QRect(150, 20, 281, 22))
        self.selectionGroupCombo.setObjectName("selectionGroupCombo")
        self.selectionGroupAddLabel = QtWidgets.QLabel(self.frame_5)
        self.selectionGroupAddLabel.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.selectionGroupAddLabel.setObjectName("selectionGroupAddLabel")
        self.selectionGroupDescr = QtWidgets.QLineEdit(self.frame_5)
        self.selectionGroupDescr.setGeometry(QtCore.QRect(240, 50, 131, 20))
        self.selectionGroupDescr.setObjectName("selectionGroupDescr")
        self.selectionGroupAddLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.selectionGroupAddLabel_2.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.selectionGroupAddLabel_2.setObjectName("selectionGroupAddLabel_2")
        self.selectionGroupName = QtWidgets.QLineEdit(self.frame_5)
        self.selectionGroupName.setGeometry(QtCore.QRect(150, 50, 81, 20))
        self.selectionGroupName.setObjectName("selectionGroupName")
        self.classDisplay = QtWidgets.QCheckBox(self.frame_5)
        self.classDisplay.setGeometry(QtCore.QRect(310, 0, 101, 17))
        self.classDisplay.setObjectName("classDisplay")
        self.selectionUp = QtWidgets.QPushButton(self.frame_29)
        self.selectionUp.setGeometry(QtCore.QRect(10, 460, 41, 31))
        self.selectionUp.setText("")
        self.selectionUp.setObjectName("selectionUp")
        self.selectionDown = QtWidgets.QPushButton(self.frame_29)
        self.selectionDown.setGeometry(QtCore.QRect(10, 550, 41, 31))
        self.selectionDown.setText("")
        self.selectionDown.setObjectName("selectionDown")
        self.selectionRemove = QtWidgets.QPushButton(self.frame_29)
        self.selectionRemove.setGeometry(QtCore.QRect(70, 630, 75, 23))
        self.selectionRemove.setObjectName("selectionRemove")
        self.groupFrame = QtWidgets.QFrame(self.frame_29)
        self.groupFrame.setGeometry(QtCore.QRect(480, 10, 341, 381))
        self.groupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupFrame.setObjectName("groupFrame")
        self.label_111 = QtWidgets.QLabel(self.groupFrame)
        self.label_111.setGeometry(QtCore.QRect(10, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.groupsView = QtWidgets.QTableView(self.groupFrame)
        self.groupsView.setGeometry(QtCore.QRect(20, 20, 321, 321))
        self.groupsView.setObjectName("groupsView")
        self.groupsRemove = QtWidgets.QPushButton(self.groupFrame)
        self.groupsRemove.setGeometry(QtCore.QRect(260, 350, 75, 23))
        self.groupsRemove.setObjectName("groupsRemove")
        self.selectionRunSelectionMode = QtWidgets.QCheckBox(self.frame_29)
        self.selectionRunSelectionMode.setGeometry(QtCore.QRect(310, 630, 241, 17))
        self.selectionRunSelectionMode.setObjectName("selectionRunSelectionMode")
        self.classFrame = QtWidgets.QFrame(self.frame_29)
        self.classFrame.setGeometry(QtCore.QRect(480, 10, 361, 381))
        self.classFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classFrame.setObjectName("classFrame")
        self.classesLabel = QtWidgets.QLabel(self.classFrame)
        self.classesLabel.setGeometry(QtCore.QRect(10, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.classesLabel.setFont(font)
        self.classesLabel.setObjectName("classesLabel")
        self.classView = QtWidgets.QTableView(self.classFrame)
        self.classView.setGeometry(QtCore.QRect(20, 20, 321, 321))
        self.classView.setObjectName("classView")
        self.classRemove = QtWidgets.QPushButton(self.classFrame)
        self.classRemove.setGeometry(QtCore.QRect(260, 350, 75, 23))
        self.classRemove.setObjectName("classRemove")
        self.pluginTabs.addTab(self.selectionTab, "")
        self.fusionTab = QtWidgets.QWidget()
        self.fusionTab.setObjectName("fusionTab")
        self.frame_11 = QtWidgets.QFrame(self.fusionTab)
        self.frame_11.setGeometry(QtCore.QRect(50, 10, 441, 621))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.fusionRemove = QtWidgets.QPushButton(self.frame_11)
        self.fusionRemove.setGeometry(QtCore.QRect(330, 510, 71, 21))
        self.fusionRemove.setObjectName("fusionRemove")
        self.bufferInGroupLabel_3 = QtWidgets.QLabel(self.frame_11)
        self.bufferInGroupLabel_3.setGeometry(QtCore.QRect(22, 40, 81, 21))
        self.bufferInGroupLabel_3.setObjectName("bufferInGroupLabel_3")
        self.fusionST = QtWidgets.QComboBox(self.frame_11)
        self.fusionST.setGeometry(QtCore.QRect(130, 40, 271, 22))
        self.fusionST.setObjectName("fusionST")
        self.label_27 = QtWidgets.QLabel(self.frame_11)
        self.label_27.setGeometry(QtCore.QRect(0, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.fusionUp = QtWidgets.QPushButton(self.frame_11)
        self.fusionUp.setGeometry(QtCore.QRect(20, 160, 41, 31))
        self.fusionUp.setText("")
        self.fusionUp.setObjectName("fusionUp")
        self.fusionDown = QtWidgets.QPushButton(self.frame_11)
        self.fusionDown.setGeometry(QtCore.QRect(20, 260, 41, 31))
        self.fusionDown.setText("")
        self.fusionDown.setObjectName("fusionDown")
        self.fusionLoadGroups = QtWidgets.QPushButton(self.frame_11)
        self.fusionLoadGroups.setGeometry(QtCore.QRect(70, 510, 111, 21))
        self.fusionLoadGroups.setObjectName("fusionLoadGroups")
        self.fusionView = QtWidgets.QTableView(self.frame_11)
        self.fusionView.setGeometry(QtCore.QRect(70, 110, 341, 391))
        self.fusionView.setObjectName("fusionView")
        self.fusionRun = QtWidgets.QPushButton(self.frame_11)
        self.fusionRun.setGeometry(QtCore.QRect(220, 540, 71, 31))
        self.fusionRun.setObjectName("fusionRun")
        self.label_30 = QtWidgets.QLabel(self.frame_11)
        self.label_30.setGeometry(QtCore.QRect(20, 80, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.pluginTabs.addTab(self.fusionTab, "")
        self.frictionTab = QtWidgets.QWidget()
        self.frictionTab.setObjectName("frictionTab")
        self.frame_10 = QtWidgets.QFrame(self.frictionTab)
        self.frame_10.setGeometry(QtCore.QRect(40, 10, 781, 641))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frictionView = QtWidgets.QTableView(self.frame_10)
        self.frictionView.setGeometry(QtCore.QRect(30, 40, 721, 421))
        self.frictionView.setObjectName("frictionView")
        self.frictionRun = QtWidgets.QPushButton(self.frame_10)
        self.frictionRun.setGeometry(QtCore.QRect(300, 490, 171, 31))
        self.frictionRun.setObjectName("frictionRun")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.frame_2 = QtWidgets.QFrame(self.frame_10)
        self.frame_2.setGeometry(QtCore.QRect(60, 540, 421, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frictionCsvFile = QgsFileWidget(self.frame_2)
        self.frictionCsvFile.setGeometry(QtCore.QRect(190, 10, 211, 27))
        self.frictionCsvFile.setObjectName("frictionCsvFile")
        self.frictionLoadFile = QgsFileWidget(self.frame_2)
        self.frictionLoadFile.setGeometry(QtCore.QRect(190, 40, 211, 27))
        self.frictionLoadFile.setObjectName("frictionLoadFile")
        self.frictionLoadLabel = QtWidgets.QLabel(self.frame_2)
        self.frictionLoadLabel.setGeometry(QtCore.QRect(0, 40, 171, 21))
        self.frictionLoadLabel.setObjectName("frictionLoadLabel")
        self.frictionSaveLabel = QtWidgets.QLabel(self.frame_2)
        self.frictionSaveLabel.setGeometry(QtCore.QRect(0, 10, 151, 21))
        self.frictionSaveLabel.setObjectName("frictionSaveLabel")
        self.frictionLoadClass = QtWidgets.QPushButton(self.frictionTab)
        self.frictionLoadClass.setGeometry(QtCore.QRect(80, 480, 111, 21))
        self.frictionLoadClass.setObjectName("frictionLoadClass")
        self.pluginTabs.addTab(self.frictionTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(40, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(60, 50, 711, 591))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pondMode = QtWidgets.QLabel(self.frame_6)
        self.pondMode.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pondMode.setFont(font)
        self.pondMode.setObjectName("pondMode")
        self.pondModeBuffer = QtWidgets.QCheckBox(self.frame_6)
        self.pondModeBuffer.setGeometry(QtCore.QRect(170, 10, 70, 17))
        self.pondModeBuffer.setObjectName("pondModeBuffer")
        self.pondModeBuffer_2 = QtWidgets.QCheckBox(self.frame_6)
        self.pondModeBuffer_2.setGeometry(QtCore.QRect(240, 10, 70, 17))
        self.pondModeBuffer_2.setObjectName("pondModeBuffer_2")
        self.pondModeBuffer_3 = QtWidgets.QCheckBox(self.frame_6)
        self.pondModeBuffer_3.setGeometry(QtCore.QRect(320, 10, 70, 17))
        self.pondModeBuffer_3.setObjectName("pondModeBuffer_3")
        self.pondInLayerLabel = QtWidgets.QLabel(self.frame_6)
        self.pondInLayerLabel.setGeometry(QtCore.QRect(10, 40, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pondInLayerLabel.setFont(font)
        self.pondInLayerLabel.setObjectName("pondInLayerLabel")
        self.pondInLayer = QgsFileWidget(self.frame_6)
        self.pondInLayer.setGeometry(QtCore.QRect(170, 40, 291, 16))
        self.pondInLayer.setObjectName("pondInLayer")
        self.pondOutLayer = QgsFileWidget(self.frame_6)
        self.pondOutLayer.setGeometry(QtCore.QRect(170, 70, 291, 16))
        self.pondOutLayer.setObjectName("pondOutLayer")
        self.pondOutLayerLabel = QtWidgets.QLabel(self.frame_6)
        self.pondOutLayerLabel.setGeometry(QtCore.QRect(10, 70, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pondOutLayerLabel.setFont(font)
        self.pondOutLayerLabel.setObjectName("pondOutLayerLabel")
        self.pondPondLabel = QtWidgets.QLabel(self.frame_6)
        self.pondPondLabel.setGeometry(QtCore.QRect(10, 100, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pondPondLabel.setFont(font)
        self.pondPondLabel.setObjectName("pondPondLabel")
        self.pondIvalFrame = QtWidgets.QFrame(self.frame_6)
        self.pondIvalFrame.setGeometry(QtCore.QRect(170, 100, 301, 241))
        self.pondIvalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pondIvalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pondIvalFrame.setObjectName("pondIvalFrame")
        self.pondIvalView = QtWidgets.QTableView(self.pondIvalFrame)
        self.pondIvalView.setGeometry(QtCore.QRect(0, 40, 291, 191))
        self.pondIvalView.setObjectName("pondIvalView")
        self.pondIvalClass = QtWidgets.QPushButton(self.pondIvalFrame)
        self.pondIvalClass.setGeometry(QtCore.QRect(0, 10, 75, 23))
        self.pondIvalClass.setObjectName("pondIvalClass")
        self.pondIvalPlus = QtWidgets.QToolButton(self.pondIvalFrame)
        self.pondIvalPlus.setGeometry(QtCore.QRect(90, 10, 21, 21))
        self.pondIvalPlus.setObjectName("pondIvalPlus")
        self.pondIvalMinus = QtWidgets.QToolButton(self.pondIvalFrame)
        self.pondIvalMinus.setGeometry(QtCore.QRect(120, 10, 21, 21))
        self.pondIvalMinus.setObjectName("pondIvalMinus")
        self.ponNbClassesLabel = QtWidgets.QLabel(self.pondIvalFrame)
        self.ponNbClassesLabel.setGeometry(QtCore.QRect(190, 10, 61, 16))
        self.ponNbClassesLabel.setObjectName("ponNbClassesLabel")
        self.ponNbClasses = QtWidgets.QSpinBox(self.pondIvalFrame)
        self.ponNbClasses.setGeometry(QtCore.QRect(250, 10, 42, 22))
        self.ponNbClasses.setObjectName("ponNbClasses")
        self.ponderationView = QtWidgets.QTableView(self.frame_6)
        self.ponderationView.setGeometry(QtCore.QRect(130, 380, 291, 191))
        self.ponderationView.setObjectName("ponderationView")
        self.pondAdd = QtWidgets.QToolButton(self.frame_6)
        self.pondAdd.setGeometry(QtCore.QRect(130, 350, 21, 21))
        self.pondAdd.setObjectName("pondAdd")
        self.pondRemove = QtWidgets.QToolButton(self.frame_6)
        self.pondRemove.setGeometry(QtCore.QRect(160, 350, 21, 21))
        self.pondRemove.setObjectName("pondRemove")
        self.pondRun = QtWidgets.QToolButton(self.frame_6)
        self.pondRun.setGeometry(QtCore.QRect(190, 350, 21, 21))
        self.pondRun.setObjectName("pondRun")
        self.toolButton_6 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_6.setGeometry(QtCore.QRect(220, 350, 21, 21))
        self.toolButton_6.setObjectName("toolButton_6")
        self.pondBufferFrame = QtWidgets.QFrame(self.frame_6)
        self.pondBufferFrame.setGeometry(QtCore.QRect(170, 100, 301, 241))
        self.pondBufferFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pondBufferFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pondBufferFrame.setObjectName("pondBufferFrame")
        self.pondBufferView = QtWidgets.QTableView(self.pondBufferFrame)
        self.pondBufferView.setGeometry(QtCore.QRect(0, 40, 291, 191))
        self.pondBufferView.setObjectName("pondBufferView")
        self.pondBufferPlus = QtWidgets.QToolButton(self.pondBufferFrame)
        self.pondBufferPlus.setGeometry(QtCore.QRect(0, 10, 21, 21))
        self.pondBufferPlus.setObjectName("pondBufferPlus")
        self.pondBufferMinus = QtWidgets.QToolButton(self.pondBufferFrame)
        self.pondBufferMinus.setGeometry(QtCore.QRect(40, 10, 21, 21))
        self.pondBufferMinus.setObjectName("pondBufferMinus")
        self.pluginTabs.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.costRun = QtWidgets.QPushButton(self.tab)
        self.costRun.setGeometry(QtCore.QRect(220, 540, 161, 31))
        self.costRun.setObjectName("costRun")
        self.costView = QtWidgets.QTableView(self.tab)
        self.costView.setGeometry(QtCore.QRect(70, 290, 451, 221))
        self.costView.setObjectName("costView")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(70, 50, 451, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.costStartRasterLabel = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel.setGeometry(QtCore.QRect(0, 40, 171, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costStartRasterLabel.setFont(font)
        self.costStartRasterLabel.setObjectName("costStartRasterLabel")
        self.costStartLayerCombo = QgsMapLayerComboBox(self.frame)
        self.costStartLayerCombo.setGeometry(QtCore.QRect(140, 60, 291, 16))
        self.costStartLayerCombo.setObjectName("costStartLayerCombo")
        self.costPermRasterCombo = QgsMapLayerComboBox(self.frame)
        self.costPermRasterCombo.setGeometry(QtCore.QRect(140, 110, 291, 16))
        self.costPermRasterCombo.setObjectName("costPermRasterCombo")
        self.costPermRasterLabel = QtWidgets.QLabel(self.frame)
        self.costPermRasterLabel.setGeometry(QtCore.QRect(0, 100, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costPermRasterLabel.setFont(font)
        self.costPermRasterLabel.setObjectName("costPermRasterLabel")
        self.costMaxVal = QgsSpinBox(self.frame)
        self.costMaxVal.setGeometry(QtCore.QRect(140, 160, 291, 20))
        self.costMaxVal.setMaximum(999999999)
        self.costMaxVal.setObjectName("costMaxVal")
        self.costMaxCost = QtWidgets.QLabel(self.frame)
        self.costMaxCost.setGeometry(QtCore.QRect(0, 160, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costMaxCost.setFont(font)
        self.costMaxCost.setObjectName("costMaxCost")
        self.costAdd = QtWidgets.QPushButton(self.frame)
        self.costAdd.setGeometry(QtCore.QRect(150, 190, 131, 21))
        self.costAdd.setObjectName("costAdd")
        self.costStartLayer = QgsFileWidget(self.frame)
        self.costStartLayer.setGeometry(QtCore.QRect(140, 80, 291, 16))
        self.costStartLayer.setObjectName("costStartLayer")
        self.costPermRaster = QgsFileWidget(self.frame)
        self.costPermRaster.setGeometry(QtCore.QRect(140, 130, 291, 16))
        self.costPermRaster.setObjectName("costPermRaster")
        self.costSTCombo = QtWidgets.QComboBox(self.frame)
        self.costSTCombo.setGeometry(QtCore.QRect(140, 10, 111, 21))
        self.costSTCombo.setObjectName("costSTCombo")
        self.costSTLabel = QtWidgets.QLabel(self.frame)
        self.costSTLabel.setGeometry(QtCore.QRect(0, 10, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costSTLabel.setFont(font)
        self.costSTLabel.setObjectName("costSTLabel")
        self.costStartRasterLabel_2 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_2.setGeometry(QtCore.QRect(30, 60, 111, 20))
        self.costStartRasterLabel_2.setObjectName("costStartRasterLabel_2")
        self.costStartRasterLabel_3 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_3.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.costStartRasterLabel_3.setObjectName("costStartRasterLabel_3")
        self.costStartRasterLabel_4 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_4.setGeometry(QtCore.QRect(30, 110, 111, 20))
        self.costStartRasterLabel_4.setObjectName("costStartRasterLabel_4")
        self.costStartRasterLabel_5 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_5.setGeometry(QtCore.QRect(30, 130, 91, 16))
        self.costStartRasterLabel_5.setObjectName("costStartRasterLabel_5")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(50, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.costRemove = QtWidgets.QPushButton(self.tab)
        self.costRemove.setGeometry(QtCore.QRect(450, 520, 75, 23))
        self.costRemove.setObjectName("costRemove")
        self.costRunSelectionMode = QtWidgets.QCheckBox(self.tab)
        self.costRunSelectionMode.setGeometry(QtCore.QRect(180, 520, 241, 17))
        self.costRunSelectionMode.setObjectName("costRunSelectionMode")
        self.pluginTabs.addTab(self.tab, "")

        self.retranslateUi(EcologicalContinuityDialogBase)
        self.pluginTabs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(EcologicalContinuityDialogBase)

    def retranslateUi(self, EcologicalContinuityDialogBase):
        _translate = QtCore.QCoreApplication.translate
        EcologicalContinuityDialogBase.setWindowTitle(_translate("EcologicalContinuityDialogBase", "BioDispersal"))
        self.paramlabel.setText(_translate("EcologicalContinuityDialogBase", "Paramètres"))
        self.label_41.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer projet sous"))
        self.paramlabel_5.setText(_translate("EcologicalContinuityDialogBase", "Projet"))
        self.label_29.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir projet"))
        self.label_42.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer projet"))
        self.saveProjectButton.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer"))
        self.label_44.setText(_translate("EcologicalContinuityDialogBase", "Dossier de travail*"))
        self.label_45.setText(_translate("EcologicalContinuityDialogBase", "Couche d\'emprise*"))
        self.label_46.setText(_translate("EcologicalContinuityDialogBase", "Résolution raster*"))
        self.label_47.setText(_translate("EcologicalContinuityDialogBase", "Projection*"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.mainTab), _translate("EcologicalContinuityDialogBase", "1 - Paramètres"))
        self.label_102.setText(_translate("EcologicalContinuityDialogBase", "Sous-trames"))
        self.stFilter.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[Filter]"))
        self.stRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer les sous-trames sélectionnées"))
        self.stAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter sous-trame"))
        self.label_103.setText(_translate("EcologicalContinuityDialogBase", "Nom"))
        self.label_104.setText(_translate("EcologicalContinuityDialogBase", "Description"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.stTab), _translate("EcologicalContinuityDialogBase", "2 - Sous-trames"))
        self.selectionRun.setText(_translate("EcologicalContinuityDialogBase", "Lancer les sélections"))
        self.selectionAdd.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer sélection"))
        self.selectionLabel.setText(_translate("EcologicalContinuityDialogBase", "Sélection"))
        self.exprSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Par expression"))
        self.selectionStep2Label.setText(_translate("EcologicalContinuityDialogBase", "2- Mode de sélection"))
        self.selectionExprLabel.setText(_translate("EcologicalContinuityDialogBase", "Expression"))
        self.selectionModeLabel.setText(_translate("EcologicalContinuityDialogBase", "Mode de sélection"))
        self.fieldSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Par champ"))
        self.selectionFieldLabel.setText(_translate("EcologicalContinuityDialogBase", "Champ"))
        self.selectionResampleLabel.setText(_translate("EcologicalContinuityDialogBase", "Mode de ré-échantillonage"))
        self.selectionExprLabel_3.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir couche"))
        self.selectionLayerLabel.setText(_translate("EcologicalContinuityDialogBase", "1 - Couche"))
        self.selectionExprLabel_2.setText(_translate("EcologicalContinuityDialogBase", "Sélectionner couche"))
        self.selectionLayerFormatLabel.setText(_translate("EcologicalContinuityDialogBase", "Format"))
        self.selectionLayerFormatVector.setText(_translate("EcologicalContinuityDialogBase", "Vecteur"))
        self.selectionLayerFormatRaster.setText(_translate("EcologicalContinuityDialogBase", "Raster"))
        self.groupDisplay.setText(_translate("EcologicalContinuityDialogBase", "Afficher groupes"))
        self.selectionGroupLabel.setText(_translate("EcologicalContinuityDialogBase", "3 - Groupe"))
        self.selectionGroupAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter"))
        self.selectionGroupAddLabel.setText(_translate("EcologicalContinuityDialogBase", "Ajouter au groupe"))
        self.selectionGroupDescr.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[description]"))
        self.selectionGroupAddLabel_2.setText(_translate("EcologicalContinuityDialogBase", "Nouveau groupe"))
        self.selectionGroupName.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[nom]"))
        self.classDisplay.setText(_translate("EcologicalContinuityDialogBase", "Afficher classes"))
        self.selectionRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.label_111.setText(_translate("EcologicalContinuityDialogBase", "Groupes"))
        self.groupsRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.selectionRunSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Appliquer seulement aux lignes sélectionnées"))
        self.classesLabel.setText(_translate("EcologicalContinuityDialogBase", "Classes"))
        self.classRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.selectionTab), _translate("EcologicalContinuityDialogBase", "3 - Selection"))
        self.fusionRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.bufferInGroupLabel_3.setText(_translate("EcologicalContinuityDialogBase", "Sous-trame"))
        self.label_27.setText(_translate("EcologicalContinuityDialogBase", "Fusion"))
        self.fusionLoadGroups.setText(_translate("EcologicalContinuityDialogBase", "Charger groupes"))
        self.fusionRun.setText(_translate("EcologicalContinuityDialogBase", "Fusionner"))
        self.label_30.setText(_translate("EcologicalContinuityDialogBase", "Hiérarchiser les couches"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.fusionTab), _translate("EcologicalContinuityDialogBase", "4 - Fusion"))
        self.frictionRun.setText(_translate("EcologicalContinuityDialogBase", "Produire les couches de friction"))
        self.label_26.setText(_translate("EcologicalContinuityDialogBase", "Friction"))
        self.frictionLoadLabel.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir le tableau"))
        self.frictionSaveLabel.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer le tableau sous"))
        self.frictionLoadClass.setText(_translate("EcologicalContinuityDialogBase", "Charger classes"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.frictionTab), _translate("EcologicalContinuityDialogBase", "5 - Friction"))
        self.label_31.setText(_translate("EcologicalContinuityDialogBase", "Pondération"))
        self.pondMode.setText(_translate("EcologicalContinuityDialogBase", "1 - Mode de pondération"))
        self.pondModeBuffer.setText(_translate("EcologicalContinuityDialogBase", "Tampon"))
        self.pondModeBuffer_2.setText(_translate("EcologicalContinuityDialogBase", "Intervalles"))
        self.pondModeBuffer_3.setText(_translate("EcologicalContinuityDialogBase", "Direct"))
        self.pondInLayerLabel.setText(_translate("EcologicalContinuityDialogBase", "2 - Couche d\'entrée"))
        self.pondOutLayerLabel.setText(_translate("EcologicalContinuityDialogBase", "3 - Couche de sortie"))
        self.pondPondLabel.setText(_translate("EcologicalContinuityDialogBase", "4 - Pondération"))
        self.pondIvalClass.setText(_translate("EcologicalContinuityDialogBase", "Classer"))
        self.pondIvalPlus.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.pondIvalMinus.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.ponNbClassesLabel.setText(_translate("EcologicalContinuityDialogBase", "Nb classes"))
        self.pondAdd.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.pondRemove.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.pondRun.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.toolButton_6.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.pondBufferPlus.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.pondBufferMinus.setText(_translate("EcologicalContinuityDialogBase", "..."))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.tab_2), _translate("EcologicalContinuityDialogBase", "6 - Pondération"))
        self.costRun.setText(_translate("EcologicalContinuityDialogBase", "Lancer la modélisation"))
        self.costStartRasterLabel.setText(_translate("EcologicalContinuityDialogBase", "2 - Réservoirs de biodiversité"))
        self.costPermRasterLabel.setText(_translate("EcologicalContinuityDialogBase", "3 - Raster de friction"))
        self.costMaxCost.setText(_translate("EcologicalContinuityDialogBase", "4 - Coût max"))
        self.costAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter dispersion"))
        self.costSTLabel.setText(_translate("EcologicalContinuityDialogBase", "1 - Sous-trame"))
        self.costStartRasterLabel_2.setText(_translate("EcologicalContinuityDialogBase", "Sélectionner couche"))
        self.costStartRasterLabel_3.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir couche"))
        self.costStartRasterLabel_4.setText(_translate("EcologicalContinuityDialogBase", "Sélectionner couche"))
        self.costStartRasterLabel_5.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir couche"))
        self.label_28.setText(_translate("EcologicalContinuityDialogBase", "Dispersion"))
        self.costRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.costRunSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Appliquer seulement aux lignes sélectionnées"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.tab), _translate("EcologicalContinuityDialogBase", "7 - Dispersion"))

from qgis.gui import QgsExtentGroupBox, QgsFieldComboBox, QgsFieldExpressionWidget, QgsFileWidget, QgsMapLayerComboBox, QgsProjectionSelectionWidget, QgsSpinBox
