# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eco_cont_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EcologicalContinuityDialogBase(object):
    def setupUi(self, EcologicalContinuityDialogBase):
        EcologicalContinuityDialogBase.setObjectName("EcologicalContinuityDialogBase")
        EcologicalContinuityDialogBase.resize(939, 780)
        self.pluginTabs = QtWidgets.QTabWidget(EcologicalContinuityDialogBase)
        self.pluginTabs.setGeometry(QtCore.QRect(40, 20, 871, 731))
        self.pluginTabs.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pluginTabs.setObjectName("pluginTabs")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.paramlabel = QtWidgets.QLabel(self.mainTab)
        self.paramlabel.setGeometry(QtCore.QRect(40, 20, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel.setFont(font)
        self.paramlabel.setObjectName("paramlabel")
        self.treatmentsFrame = QtWidgets.QFrame(self.mainTab)
        self.treatmentsFrame.setGeometry(QtCore.QRect(610, 340, 201, 211))
        self.treatmentsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treatmentsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.treatmentsFrame.setObjectName("treatmentsFrame")
        self.paramlabel_4 = QtWidgets.QLabel(self.treatmentsFrame)
        self.paramlabel_4.setGeometry(QtCore.QRect(0, 0, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel_4.setFont(font)
        self.paramlabel_4.setObjectName("paramlabel_4")
        self.runGroupCB = QtWidgets.QCheckBox(self.treatmentsFrame)
        self.runGroupCB.setGeometry(QtCore.QRect(150, 30, 16, 17))
        self.runGroupCB.setText("")
        self.runGroupCB.setObjectName("runGroupCB")
        self.label_24 = QtWidgets.QLabel(self.treatmentsFrame)
        self.label_24.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label_24.setObjectName("label_24")
        self.label_35 = QtWidgets.QLabel(self.treatmentsFrame)
        self.label_35.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label_35.setObjectName("label_35")
        self.runMetagroupCB = QtWidgets.QCheckBox(self.treatmentsFrame)
        self.runMetagroupCB.setGeometry(QtCore.QRect(150, 50, 16, 17))
        self.runMetagroupCB.setText("")
        self.runMetagroupCB.setObjectName("runMetagroupCB")
        self.label_36 = QtWidgets.QLabel(self.treatmentsFrame)
        self.label_36.setGeometry(QtCore.QRect(30, 70, 111, 16))
        self.label_36.setObjectName("label_36")
        self.runSelectionCB = QtWidgets.QCheckBox(self.treatmentsFrame)
        self.runSelectionCB.setGeometry(QtCore.QRect(150, 70, 16, 17))
        self.runSelectionCB.setText("")
        self.runSelectionCB.setObjectName("runSelectionCB")
        self.label_37 = QtWidgets.QLabel(self.treatmentsFrame)
        self.label_37.setGeometry(QtCore.QRect(30, 90, 111, 16))
        self.label_37.setObjectName("label_37")
        self.runTamponCB = QtWidgets.QCheckBox(self.treatmentsFrame)
        self.runTamponCB.setGeometry(QtCore.QRect(150, 90, 16, 17))
        self.runTamponCB.setText("")
        self.runTamponCB.setObjectName("runTamponCB")
        self.label_38 = QtWidgets.QLabel(self.treatmentsFrame)
        self.label_38.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.label_38.setObjectName("label_38")
        self.runRasterizationCB = QtWidgets.QCheckBox(self.treatmentsFrame)
        self.runRasterizationCB.setGeometry(QtCore.QRect(150, 110, 16, 17))
        self.runRasterizationCB.setText("")
        self.runRasterizationCB.setObjectName("runRasterizationCB")
        self.label_39 = QtWidgets.QLabel(self.treatmentsFrame)
        self.label_39.setGeometry(QtCore.QRect(30, 130, 111, 16))
        self.label_39.setObjectName("label_39")
        self.runFrictionCB = QtWidgets.QCheckBox(self.treatmentsFrame)
        self.runFrictionCB.setGeometry(QtCore.QRect(150, 130, 16, 17))
        self.runFrictionCB.setText("")
        self.runFrictionCB.setObjectName("runFrictionCB")
        self.label_40 = QtWidgets.QLabel(self.treatmentsFrame)
        self.label_40.setGeometry(QtCore.QRect(30, 150, 111, 16))
        self.label_40.setObjectName("label_40")
        self.runCostCB = QtWidgets.QCheckBox(self.treatmentsFrame)
        self.runCostCB.setGeometry(QtCore.QRect(150, 150, 16, 17))
        self.runCostCB.setText("")
        self.runCostCB.setObjectName("runCostCB")
        self.pushButton = QtWidgets.QPushButton(self.treatmentsFrame)
        self.pushButton.setGeometry(QtCore.QRect(90, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.frame_9 = QtWidgets.QFrame(self.mainTab)
        self.frame_9.setGeometry(QtCore.QRect(40, 380, 361, 131))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.saveModelPath = QgsFileWidget(self.frame_9)
        self.saveModelPath.setGeometry(QtCore.QRect(160, 50, 171, 27))
        self.saveModelPath.setObjectName("saveModelPath")
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        self.label_41.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label_41.setObjectName("label_41")
        self.paramlabel_5 = QtWidgets.QLabel(self.frame_9)
        self.paramlabel_5.setGeometry(QtCore.QRect(0, 0, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paramlabel_5.setFont(font)
        self.paramlabel_5.setObjectName("paramlabel_5")
        self.loadModelPath = QgsFileWidget(self.frame_9)
        self.loadModelPath.setGeometry(QtCore.QRect(160, 20, 171, 27))
        self.loadModelPath.setObjectName("loadModelPath")
        self.label_29 = QtWidgets.QLabel(self.frame_9)
        self.label_29.setGeometry(QtCore.QRect(30, 20, 111, 16))
        self.label_29.setObjectName("label_29")
        self.label_42 = QtWidgets.QLabel(self.frame_9)
        self.label_42.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.label_42.setObjectName("label_42")
        self.saveProjectButton = QtWidgets.QPushButton(self.frame_9)
        self.saveProjectButton.setGeometry(QtCore.QRect(160, 80, 75, 23))
        self.saveProjectButton.setObjectName("saveProjectButton")
        self.frame_12 = QtWidgets.QFrame(self.mainTab)
        self.frame_12.setGeometry(QtCore.QRect(70, 50, 461, 121))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.workspace = QgsFileWidget(self.frame_12)
        self.workspace.setGeometry(QtCore.QRect(110, 0, 261, 21))
        self.workspace.setObjectName("workspace")
        self.label_44 = QtWidgets.QLabel(self.frame_12)
        self.label_44.setGeometry(QtCore.QRect(0, 0, 111, 16))
        self.label_44.setObjectName("label_44")
        self.extentLayer = QgsFileWidget(self.frame_12)
        self.extentLayer.setGeometry(QtCore.QRect(110, 30, 261, 21))
        self.extentLayer.setObjectName("extentLayer")
        self.label_45 = QtWidgets.QLabel(self.frame_12)
        self.label_45.setGeometry(QtCore.QRect(1, 30, 111, 16))
        self.label_45.setObjectName("label_45")
        self.rasterResolution = QgsSpinBox(self.frame_12)
        self.rasterResolution.setGeometry(QtCore.QRect(110, 60, 261, 21))
        self.rasterResolution.setMaximum(999999)
        self.rasterResolution.setObjectName("rasterResolution")
        self.label_46 = QtWidgets.QLabel(self.frame_12)
        self.label_46.setGeometry(QtCore.QRect(1, 60, 111, 16))
        self.label_46.setObjectName("label_46")
        self.paramsCrs = QgsProjectionSelectionWidget(self.frame_12)
        self.paramsCrs.setGeometry(QtCore.QRect(110, 90, 261, 21))
        self.paramsCrs.setObjectName("paramsCrs")
        self.label_47 = QtWidgets.QLabel(self.frame_12)
        self.label_47.setGeometry(QtCore.QRect(0, 90, 111, 16))
        self.label_47.setObjectName("label_47")
        self.paramsView = QtWidgets.QTableView(self.mainTab)
        self.paramsView.setGeometry(QtCore.QRect(40, 180, 511, 171))
        self.paramsView.setObjectName("paramsView")
        self.options2Frame = QtWidgets.QFrame(self.mainTab)
        self.options2Frame.setGeometry(QtCore.QRect(560, 50, 261, 71))
        self.options2Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options2Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options2Frame.setObjectName("options2Frame")
        self.paramsRelPath = QtWidgets.QCheckBox(self.options2Frame)
        self.paramsRelPath.setGeometry(QtCore.QRect(240, 10, 16, 17))
        self.paramsRelPath.setText("")
        self.paramsRelPath.setObjectName("paramsRelPath")
        self.label_108 = QtWidgets.QLabel(self.options2Frame)
        self.label_108.setGeometry(QtCore.QRect(0, 50, 211, 16))
        self.label_108.setObjectName("label_108")
        self.eraseExisting = QtWidgets.QCheckBox(self.options2Frame)
        self.eraseExisting.setGeometry(QtCore.QRect(240, 30, 16, 17))
        self.eraseExisting.setText("")
        self.eraseExisting.setChecked(True)
        self.eraseExisting.setObjectName("eraseExisting")
        self.displayVisu = QtWidgets.QCheckBox(self.options2Frame)
        self.displayVisu.setGeometry(QtCore.QRect(240, 50, 16, 17))
        self.displayVisu.setObjectName("displayVisu")
        self.label_107 = QtWidgets.QLabel(self.options2Frame)
        self.label_107.setGeometry(QtCore.QRect(0, 30, 151, 16))
        self.label_107.setObjectName("label_107")
        self.useRelPathLabel = QtWidgets.QLabel(self.options2Frame)
        self.useRelPathLabel.setGeometry(QtCore.QRect(0, 10, 141, 16))
        self.useRelPathLabel.setObjectName("useRelPathLabel")
        self.pluginTabs.addTab(self.mainTab, "")
        self.stTab = QtWidgets.QWidget()
        self.stTab.setObjectName("stTab")
        self.frame_28 = QtWidgets.QFrame(self.stTab)
        self.frame_28.setGeometry(QtCore.QRect(30, 20, 441, 401))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.stView = QtWidgets.QTableView(self.frame_28)
        self.stView.setGeometry(QtCore.QRect(10, 110, 401, 271))
        self.stView.setObjectName("stView")
        self.label_102 = QtWidgets.QLabel(self.frame_28)
        self.label_102.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.stFilter = QtWidgets.QLineEdit(self.frame_28)
        self.stFilter.setGeometry(QtCore.QRect(20, 80, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stFilter.setFont(font)
        self.stFilter.setObjectName("stFilter")
        self.stRemove = QtWidgets.QPushButton(self.frame_28)
        self.stRemove.setGeometry(QtCore.QRect(190, 80, 211, 23))
        self.stRemove.setObjectName("stRemove")
        self.stAdd = QtWidgets.QPushButton(self.frame_28)
        self.stAdd.setGeometry(QtCore.QRect(40, 80, 111, 23))
        self.stAdd.setObjectName("stAdd")
        self.stDescr = QtWidgets.QLineEdit(self.frame_28)
        self.stDescr.setGeometry(QtCore.QRect(120, 50, 281, 20))
        self.stDescr.setObjectName("stDescr")
        self.stName = QtWidgets.QLineEdit(self.frame_28)
        self.stName.setGeometry(QtCore.QRect(120, 20, 281, 20))
        self.stName.setObjectName("stName")
        self.label_103 = QtWidgets.QLabel(self.frame_28)
        self.label_103.setGeometry(QtCore.QRect(40, 20, 47, 13))
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.frame_28)
        self.label_104.setGeometry(QtCore.QRect(40, 50, 61, 16))
        self.label_104.setObjectName("label_104")
        self.pluginTabs.addTab(self.stTab, "")
        self.selectionTab = QtWidgets.QWidget()
        self.selectionTab.setObjectName("selectionTab")
        self.frame_29 = QtWidgets.QFrame(self.selectionTab)
        self.frame_29.setGeometry(QtCore.QRect(10, 10, 841, 691))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.selectionView = QtWidgets.QTableView(self.frame_29)
        self.selectionView.setGeometry(QtCore.QRect(60, 430, 761, 192))
        self.selectionView.setObjectName("selectionView")
        self.selectionRun = QtWidgets.QPushButton(self.frame_29)
        self.selectionRun.setGeometry(QtCore.QRect(390, 650, 131, 31))
        self.selectionRun.setObjectName("selectionRun")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setGeometry(QtCore.QRect(10, 10, 441, 411))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.selectionGroupCombo = QtWidgets.QComboBox(self.frame_30)
        self.selectionGroupCombo.setGeometry(QtCore.QRect(160, 300, 281, 22))
        self.selectionGroupCombo.setObjectName("selectionGroupCombo")
        self.selectionExpr = QgsFieldExpressionWidget(self.frame_30)
        self.selectionExpr.setGeometry(QtCore.QRect(160, 150, 281, 21))
        self.selectionExpr.setObjectName("selectionExpr")
        self.selectionGroupLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionGroupLabel.setGeometry(QtCore.QRect(10, 280, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionGroupLabel.setFont(font)
        self.selectionGroupLabel.setObjectName("selectionGroupLabel")
        self.selectionGroupName = QtWidgets.QLineEdit(self.frame_30)
        self.selectionGroupName.setGeometry(QtCore.QRect(160, 330, 81, 20))
        self.selectionGroupName.setObjectName("selectionGroupName")
        self.selectionStep2Label = QtWidgets.QLabel(self.frame_30)
        self.selectionStep2Label.setGeometry(QtCore.QRect(10, 110, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionStep2Label.setFont(font)
        self.selectionStep2Label.setObjectName("selectionStep2Label")
        self.selectionInLayer = QgsFileWidget(self.frame_30)
        self.selectionInLayer.setGeometry(QtCore.QRect(160, 70, 281, 27))
        self.selectionInLayer.setObjectName("selectionInLayer")
        self.selectionLayerLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionLayerLabel.setGeometry(QtCore.QRect(10, 30, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionLayerLabel.setFont(font)
        self.selectionLayerLabel.setObjectName("selectionLayerLabel")
        self.selectionInLayerCombo = QgsMapLayerComboBox(self.frame_30)
        self.selectionInLayerCombo.setGeometry(QtCore.QRect(160, 50, 281, 21))
        self.selectionInLayerCombo.setObjectName("selectionInLayerCombo")
        self.selectionAdd = QtWidgets.QPushButton(self.frame_30)
        self.selectionAdd.setGeometry(QtCore.QRect(200, 370, 121, 23))
        self.selectionAdd.setObjectName("selectionAdd")
        self.selectionClassLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionClassLabel.setGeometry(QtCore.QRect(10, 190, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectionClassLabel.setFont(font)
        self.selectionClassLabel.setObjectName("selectionClassLabel")
        self.selectionClassDescr = QtWidgets.QLineEdit(self.frame_30)
        self.selectionClassDescr.setGeometry(QtCore.QRect(250, 240, 131, 20))
        self.selectionClassDescr.setObjectName("selectionClassDescr")
        self.selectionClassCombo = QtWidgets.QComboBox(self.frame_30)
        self.selectionClassCombo.setGeometry(QtCore.QRect(160, 210, 281, 22))
        self.selectionClassCombo.setObjectName("selectionClassCombo")
        self.selectionFieldLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionFieldLabel.setGeometry(QtCore.QRect(30, 150, 61, 21))
        self.selectionFieldLabel.setObjectName("selectionFieldLabel")
        self.selectionField = QgsFieldComboBox(self.frame_30)
        self.selectionField.setGeometry(QtCore.QRect(160, 150, 281, 21))
        self.selectionField.setObjectName("selectionField")
        self.selectionClassName = QtWidgets.QLineEdit(self.frame_30)
        self.selectionClassName.setGeometry(QtCore.QRect(160, 240, 81, 20))
        self.selectionClassName.setObjectName("selectionClassName")
        self.selectionGroupDescr = QtWidgets.QLineEdit(self.frame_30)
        self.selectionGroupDescr.setGeometry(QtCore.QRect(250, 330, 131, 20))
        self.selectionGroupDescr.setObjectName("selectionGroupDescr")
        self.selectionLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionLabel.setGeometry(QtCore.QRect(30, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selectionLabel.setFont(font)
        self.selectionLabel.setObjectName("selectionLabel")
        self.fieldSelectionMode = QtWidgets.QCheckBox(self.frame_30)
        self.fieldSelectionMode.setGeometry(QtCore.QRect(180, 130, 70, 17))
        self.fieldSelectionMode.setObjectName("fieldSelectionMode")
        self.selectionModeLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionModeLabel.setGeometry(QtCore.QRect(30, 130, 101, 21))
        self.selectionModeLabel.setObjectName("selectionModeLabel")
        self.exprSelectionMode = QtWidgets.QCheckBox(self.frame_30)
        self.exprSelectionMode.setGeometry(QtCore.QRect(310, 130, 101, 17))
        self.exprSelectionMode.setObjectName("exprSelectionMode")
        self.selectionExprLabel_2 = QtWidgets.QLabel(self.frame_30)
        self.selectionExprLabel_2.setGeometry(QtCore.QRect(30, 50, 101, 21))
        self.selectionExprLabel_2.setObjectName("selectionExprLabel_2")
        self.selectionExprLabel_3 = QtWidgets.QLabel(self.frame_30)
        self.selectionExprLabel_3.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.selectionExprLabel_3.setObjectName("selectionExprLabel_3")
        self.selectionExprLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionExprLabel.setGeometry(QtCore.QRect(30, 150, 61, 21))
        self.selectionExprLabel.setObjectName("selectionExprLabel")
        self.selectionClassAddLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionClassAddLabel.setGeometry(QtCore.QRect(30, 210, 101, 21))
        self.selectionClassAddLabel.setObjectName("selectionClassAddLabel")
        self.selectionClassNewLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionClassNewLabel.setGeometry(QtCore.QRect(30, 240, 101, 21))
        self.selectionClassNewLabel.setObjectName("selectionClassNewLabel")
        self.selectionGroupAddLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionGroupAddLabel.setGeometry(QtCore.QRect(30, 300, 101, 21))
        self.selectionGroupAddLabel.setObjectName("selectionGroupAddLabel")
        self.selectionGroupAddLabel_2 = QtWidgets.QLabel(self.frame_30)
        self.selectionGroupAddLabel_2.setGeometry(QtCore.QRect(30, 330, 101, 21))
        self.selectionGroupAddLabel_2.setObjectName("selectionGroupAddLabel_2")
        self.selectionFieldClassLabel = QtWidgets.QLabel(self.frame_30)
        self.selectionFieldClassLabel.setGeometry(QtCore.QRect(160, 200, 281, 61))
        font = QtGui.QFont()
        font.setKerning(True)
        self.selectionFieldClassLabel.setFont(font)
        self.selectionFieldClassLabel.setTextFormat(QtCore.Qt.AutoText)
        self.selectionFieldClassLabel.setWordWrap(True)
        self.selectionFieldClassLabel.setObjectName("selectionFieldClassLabel")
        self.selectionGroupAdd = QtWidgets.QPushButton(self.frame_30)
        self.selectionGroupAdd.setGeometry(QtCore.QRect(390, 330, 51, 23))
        self.selectionGroupAdd.setObjectName("selectionGroupAdd")
        self.selectionClassAdd = QtWidgets.QPushButton(self.frame_30)
        self.selectionClassAdd.setGeometry(QtCore.QRect(390, 240, 51, 23))
        self.selectionClassAdd.setObjectName("selectionClassAdd")
        self.groupDisplay = QtWidgets.QCheckBox(self.frame_30)
        self.groupDisplay.setGeometry(QtCore.QRect(160, 280, 70, 17))
        self.groupDisplay.setObjectName("groupDisplay")
        self.classDisplay = QtWidgets.QCheckBox(self.frame_30)
        self.classDisplay.setGeometry(QtCore.QRect(160, 190, 70, 17))
        self.classDisplay.setObjectName("classDisplay")
        self.selectionUp = QtWidgets.QPushButton(self.frame_29)
        self.selectionUp.setGeometry(QtCore.QRect(10, 460, 41, 31))
        self.selectionUp.setText("")
        self.selectionUp.setObjectName("selectionUp")
        self.selectionDown = QtWidgets.QPushButton(self.frame_29)
        self.selectionDown.setGeometry(QtCore.QRect(10, 560, 41, 31))
        self.selectionDown.setText("")
        self.selectionDown.setObjectName("selectionDown")
        self.selectionRemove = QtWidgets.QPushButton(self.frame_29)
        self.selectionRemove.setGeometry(QtCore.QRect(70, 630, 75, 23))
        self.selectionRemove.setObjectName("selectionRemove")
        self.groupFrame = QtWidgets.QFrame(self.frame_29)
        self.groupFrame.setGeometry(QtCore.QRect(480, 10, 341, 411))
        self.groupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupFrame.setObjectName("groupFrame")
        self.label_111 = QtWidgets.QLabel(self.groupFrame)
        self.label_111.setGeometry(QtCore.QRect(20, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.groupsView = QtWidgets.QTableView(self.groupFrame)
        self.groupsView.setGeometry(QtCore.QRect(20, 40, 321, 321))
        self.groupsView.setObjectName("groupsView")
        self.groupsRemove = QtWidgets.QPushButton(self.groupFrame)
        self.groupsRemove.setGeometry(QtCore.QRect(260, 370, 75, 23))
        self.groupsRemove.setObjectName("groupsRemove")
        self.classFrame = QtWidgets.QFrame(self.frame_29)
        self.classFrame.setGeometry(QtCore.QRect(480, 10, 411, 371))
        self.classFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classFrame.setObjectName("classFrame")
        self.classesLabel = QtWidgets.QLabel(self.classFrame)
        self.classesLabel.setGeometry(QtCore.QRect(20, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.classesLabel.setFont(font)
        self.classesLabel.setObjectName("classesLabel")
        self.classView = QtWidgets.QTableView(self.classFrame)
        self.classView.setGeometry(QtCore.QRect(20, 40, 321, 321))
        self.classView.setObjectName("classView")
        self.pluginTabs.addTab(self.selectionTab, "")
        self.fusionTab = QtWidgets.QWidget()
        self.fusionTab.setObjectName("fusionTab")
        self.frame_11 = QtWidgets.QFrame(self.fusionTab)
        self.frame_11.setGeometry(QtCore.QRect(50, 10, 411, 501))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.fusionRemove = QtWidgets.QPushButton(self.frame_11)
        self.fusionRemove.setGeometry(QtCore.QRect(330, 360, 71, 21))
        self.fusionRemove.setObjectName("fusionRemove")
        self.bufferInGroupLabel_3 = QtWidgets.QLabel(self.frame_11)
        self.bufferInGroupLabel_3.setGeometry(QtCore.QRect(22, 40, 81, 21))
        self.bufferInGroupLabel_3.setObjectName("bufferInGroupLabel_3")
        self.fusionST = QtWidgets.QComboBox(self.frame_11)
        self.fusionST.setGeometry(QtCore.QRect(130, 40, 271, 22))
        self.fusionST.setObjectName("fusionST")
        self.label_27 = QtWidgets.QLabel(self.frame_11)
        self.label_27.setGeometry(QtCore.QRect(0, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.fusionUp = QtWidgets.QPushButton(self.frame_11)
        self.fusionUp.setGeometry(QtCore.QRect(20, 160, 41, 31))
        self.fusionUp.setText("")
        self.fusionUp.setObjectName("fusionUp")
        self.fusionDown = QtWidgets.QPushButton(self.frame_11)
        self.fusionDown.setGeometry(QtCore.QRect(20, 260, 41, 31))
        self.fusionDown.setText("")
        self.fusionDown.setObjectName("fusionDown")
        self.fusionLoadGroups = QtWidgets.QPushButton(self.frame_11)
        self.fusionLoadGroups.setGeometry(QtCore.QRect(70, 360, 111, 21))
        self.fusionLoadGroups.setObjectName("fusionLoadGroups")
        self.fusionView = QtWidgets.QTableView(self.frame_11)
        self.fusionView.setGeometry(QtCore.QRect(70, 110, 341, 241))
        self.fusionView.setObjectName("fusionView")
        self.fusionRun = QtWidgets.QPushButton(self.frame_11)
        self.fusionRun.setGeometry(QtCore.QRect(220, 390, 71, 31))
        self.fusionRun.setObjectName("fusionRun")
        self.label_30 = QtWidgets.QLabel(self.frame_11)
        self.label_30.setGeometry(QtCore.QRect(20, 80, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.pluginTabs.addTab(self.fusionTab, "")
        self.frictionTab = QtWidgets.QWidget()
        self.frictionTab.setObjectName("frictionTab")
        self.frame_10 = QtWidgets.QFrame(self.frictionTab)
        self.frame_10.setGeometry(QtCore.QRect(40, 10, 781, 641))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frictionView = QtWidgets.QTableView(self.frame_10)
        self.frictionView.setGeometry(QtCore.QRect(30, 40, 721, 421))
        self.frictionView.setObjectName("frictionView")
        self.frictionRun = QtWidgets.QPushButton(self.frame_10)
        self.frictionRun.setGeometry(QtCore.QRect(300, 490, 171, 31))
        self.frictionRun.setObjectName("frictionRun")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.frame_2 = QtWidgets.QFrame(self.frame_10)
        self.frame_2.setGeometry(QtCore.QRect(60, 540, 421, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frictionCsvFile = QgsFileWidget(self.frame_2)
        self.frictionCsvFile.setGeometry(QtCore.QRect(190, 10, 211, 27))
        self.frictionCsvFile.setObjectName("frictionCsvFile")
        self.frictionLoadFile = QgsFileWidget(self.frame_2)
        self.frictionLoadFile.setGeometry(QtCore.QRect(190, 40, 211, 27))
        self.frictionLoadFile.setObjectName("frictionLoadFile")
        self.frictionLoadLabel = QtWidgets.QLabel(self.frame_2)
        self.frictionLoadLabel.setGeometry(QtCore.QRect(0, 40, 171, 21))
        self.frictionLoadLabel.setObjectName("frictionLoadLabel")
        self.frictionSaveLabel = QtWidgets.QLabel(self.frame_2)
        self.frictionSaveLabel.setGeometry(QtCore.QRect(0, 10, 151, 21))
        self.frictionSaveLabel.setObjectName("frictionSaveLabel")
        self.pluginTabs.addTab(self.frictionTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.costRun = QtWidgets.QPushButton(self.tab)
        self.costRun.setGeometry(QtCore.QRect(220, 540, 161, 31))
        self.costRun.setObjectName("costRun")
        self.costView = QtWidgets.QTableView(self.tab)
        self.costView.setGeometry(QtCore.QRect(70, 290, 451, 221))
        self.costView.setObjectName("costView")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(70, 50, 451, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.costStartRasterLabel = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel.setGeometry(QtCore.QRect(0, 40, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costStartRasterLabel.setFont(font)
        self.costStartRasterLabel.setObjectName("costStartRasterLabel")
        self.costStartLayerCombo = QgsMapLayerComboBox(self.frame)
        self.costStartLayerCombo.setGeometry(QtCore.QRect(140, 60, 291, 16))
        self.costStartLayerCombo.setObjectName("costStartLayerCombo")
        self.costPermRasterCombo = QgsMapLayerComboBox(self.frame)
        self.costPermRasterCombo.setGeometry(QtCore.QRect(140, 110, 291, 16))
        self.costPermRasterCombo.setObjectName("costPermRasterCombo")
        self.costPermRasterLabel = QtWidgets.QLabel(self.frame)
        self.costPermRasterLabel.setGeometry(QtCore.QRect(0, 100, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costPermRasterLabel.setFont(font)
        self.costPermRasterLabel.setObjectName("costPermRasterLabel")
        self.costMaxVal = QgsSpinBox(self.frame)
        self.costMaxVal.setGeometry(QtCore.QRect(140, 160, 291, 20))
        self.costMaxVal.setMaximum(999999999)
        self.costMaxVal.setObjectName("costMaxVal")
        self.costMaxCost = QtWidgets.QLabel(self.frame)
        self.costMaxCost.setGeometry(QtCore.QRect(0, 160, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costMaxCost.setFont(font)
        self.costMaxCost.setObjectName("costMaxCost")
        self.costAdd = QtWidgets.QPushButton(self.frame)
        self.costAdd.setGeometry(QtCore.QRect(150, 190, 131, 21))
        self.costAdd.setObjectName("costAdd")
        self.costStartLayer = QgsFileWidget(self.frame)
        self.costStartLayer.setGeometry(QtCore.QRect(140, 80, 291, 16))
        self.costStartLayer.setObjectName("costStartLayer")
        self.costPermRaster = QgsFileWidget(self.frame)
        self.costPermRaster.setGeometry(QtCore.QRect(140, 130, 291, 16))
        self.costPermRaster.setObjectName("costPermRaster")
        self.costSTCombo = QtWidgets.QComboBox(self.frame)
        self.costSTCombo.setGeometry(QtCore.QRect(118, 10, 111, 21))
        self.costSTCombo.setObjectName("costSTCombo")
        self.costSTLabel = QtWidgets.QLabel(self.frame)
        self.costSTLabel.setGeometry(QtCore.QRect(0, 10, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.costSTLabel.setFont(font)
        self.costSTLabel.setObjectName("costSTLabel")
        self.costStartRasterLabel_2 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_2.setGeometry(QtCore.QRect(30, 60, 111, 20))
        self.costStartRasterLabel_2.setObjectName("costStartRasterLabel_2")
        self.costStartRasterLabel_3 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_3.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.costStartRasterLabel_3.setObjectName("costStartRasterLabel_3")
        self.costStartRasterLabel_4 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_4.setGeometry(QtCore.QRect(30, 110, 111, 20))
        self.costStartRasterLabel_4.setObjectName("costStartRasterLabel_4")
        self.costStartRasterLabel_5 = QtWidgets.QLabel(self.frame)
        self.costStartRasterLabel_5.setGeometry(QtCore.QRect(30, 130, 91, 16))
        self.costStartRasterLabel_5.setObjectName("costStartRasterLabel_5")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(50, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.costRemove = QtWidgets.QPushButton(self.tab)
        self.costRemove.setGeometry(QtCore.QRect(450, 520, 75, 23))
        self.costRemove.setObjectName("costRemove")
        self.pluginTabs.addTab(self.tab, "")

        self.retranslateUi(EcologicalContinuityDialogBase)
        self.pluginTabs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(EcologicalContinuityDialogBase)

    def retranslateUi(self, EcologicalContinuityDialogBase):
        _translate = QtCore.QCoreApplication.translate
        EcologicalContinuityDialogBase.setWindowTitle(_translate("EcologicalContinuityDialogBase", "BioDispersal"))
        self.paramlabel.setText(_translate("EcologicalContinuityDialogBase", "Paramètres"))
        self.paramlabel_4.setText(_translate("EcologicalContinuityDialogBase", "Lancer traitements"))
        self.label_24.setText(_translate("EcologicalContinuityDialogBase", "Groups"))
        self.label_35.setText(_translate("EcologicalContinuityDialogBase", "Metagroups"))
        self.label_36.setText(_translate("EcologicalContinuityDialogBase", "Sélection"))
        self.label_37.setText(_translate("EcologicalContinuityDialogBase", "Tampons"))
        self.label_38.setText(_translate("EcologicalContinuityDialogBase", "Rasterization"))
        self.label_39.setText(_translate("EcologicalContinuityDialogBase", "Friction"))
        self.label_40.setText(_translate("EcologicalContinuityDialogBase", "Coût cumulé"))
        self.pushButton.setText(_translate("EcologicalContinuityDialogBase", "Run"))
        self.label_41.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer projet sous"))
        self.paramlabel_5.setText(_translate("EcologicalContinuityDialogBase", "Projet"))
        self.label_29.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir projet"))
        self.label_42.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer projet"))
        self.saveProjectButton.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer"))
        self.label_44.setText(_translate("EcologicalContinuityDialogBase", "Dossier de travail*"))
        self.label_45.setText(_translate("EcologicalContinuityDialogBase", "Couche d\'emprise*"))
        self.label_46.setText(_translate("EcologicalContinuityDialogBase", "Résolution raster*"))
        self.label_47.setText(_translate("EcologicalContinuityDialogBase", "Projection*"))
        self.label_108.setText(_translate("EcologicalContinuityDialogBase", "Afficher l\'onglet de visualisation"))
        self.displayVisu.setText(_translate("EcologicalContinuityDialogBase", "Afficher l\'onglet de visualisation"))
        self.label_107.setText(_translate("EcologicalContinuityDialogBase", "Écraser les fichiers existants"))
        self.useRelPathLabel.setText(_translate("EcologicalContinuityDialogBase", "Chemins de fichiers relatifs"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.mainTab), _translate("EcologicalContinuityDialogBase", "1 - Paramètres"))
        self.label_102.setText(_translate("EcologicalContinuityDialogBase", "Sous-trames"))
        self.stFilter.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[Filter]"))
        self.stRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer les sous-trames sélectionnées"))
        self.stAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter sous-trame"))
        self.label_103.setText(_translate("EcologicalContinuityDialogBase", "Nom"))
        self.label_104.setText(_translate("EcologicalContinuityDialogBase", "Description"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.stTab), _translate("EcologicalContinuityDialogBase", "2 - Sous-trames"))
        self.selectionRun.setText(_translate("EcologicalContinuityDialogBase", "Appliquer sélections"))
        self.selectionGroupLabel.setText(_translate("EcologicalContinuityDialogBase", "4 - Groupe"))
        self.selectionGroupName.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[nom]"))
        self.selectionStep2Label.setText(_translate("EcologicalContinuityDialogBase", "2 - Expression"))
        self.selectionLayerLabel.setText(_translate("EcologicalContinuityDialogBase", "1 - Couche"))
        self.selectionAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter sélection"))
        self.selectionClassLabel.setText(_translate("EcologicalContinuityDialogBase", "3 - Classe"))
        self.selectionClassDescr.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[description]"))
        self.selectionFieldLabel.setText(_translate("EcologicalContinuityDialogBase", "Champ"))
        self.selectionClassName.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[nom]"))
        self.selectionGroupDescr.setPlaceholderText(_translate("EcologicalContinuityDialogBase", "[description]"))
        self.selectionLabel.setText(_translate("EcologicalContinuityDialogBase", "Sélection"))
        self.fieldSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Par champ"))
        self.selectionModeLabel.setText(_translate("EcologicalContinuityDialogBase", "Mode de sélection"))
        self.exprSelectionMode.setText(_translate("EcologicalContinuityDialogBase", "Par expression"))
        self.selectionExprLabel_2.setText(_translate("EcologicalContinuityDialogBase", "Sélectionner couche"))
        self.selectionExprLabel_3.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir couche"))
        self.selectionExprLabel.setText(_translate("EcologicalContinuityDialogBase", "Expression"))
        self.selectionClassAddLabel.setText(_translate("EcologicalContinuityDialogBase", "Ajouter à la classe"))
        self.selectionClassNewLabel.setText(_translate("EcologicalContinuityDialogBase", "Nouvelle classe"))
        self.selectionGroupAddLabel.setText(_translate("EcologicalContinuityDialogBase", "Ajouter au groupe"))
        self.selectionGroupAddLabel_2.setText(_translate("EcologicalContinuityDialogBase", "Nouveau groupe"))
        self.selectionFieldClassLabel.setText(_translate("EcologicalContinuityDialogBase", "En mode de sélection par champ, les classes sont automatiquement générées à partir des valeurs v1, v2, ... du champ et du groupe sélectionnés. Par exemple : group_v1, group_v2, ..."))
        self.selectionGroupAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter"))
        self.selectionClassAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter"))
        self.groupDisplay.setText(_translate("EcologicalContinuityDialogBase", "Afficher"))
        self.classDisplay.setText(_translate("EcologicalContinuityDialogBase", "Afficher"))
        self.selectionRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.label_111.setText(_translate("EcologicalContinuityDialogBase", "Groupes"))
        self.groupsRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.classesLabel.setText(_translate("EcologicalContinuityDialogBase", "Classes"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.selectionTab), _translate("EcologicalContinuityDialogBase", "3 - Selection"))
        self.fusionRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.bufferInGroupLabel_3.setText(_translate("EcologicalContinuityDialogBase", "Sous-trame"))
        self.label_27.setText(_translate("EcologicalContinuityDialogBase", "Fusion"))
        self.fusionLoadGroups.setText(_translate("EcologicalContinuityDialogBase", "Charger groupes"))
        self.fusionRun.setText(_translate("EcologicalContinuityDialogBase", "Fusionner"))
        self.label_30.setText(_translate("EcologicalContinuityDialogBase", "Hiérarchiser les couches"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.fusionTab), _translate("EcologicalContinuityDialogBase", "4 - Fusion"))
        self.frictionRun.setText(_translate("EcologicalContinuityDialogBase", "Produire les couches de friction"))
        self.label_26.setText(_translate("EcologicalContinuityDialogBase", "Friction"))
        self.frictionLoadLabel.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir le tableau"))
        self.frictionSaveLabel.setText(_translate("EcologicalContinuityDialogBase", "Enregistrer le tableau sous"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.frictionTab), _translate("EcologicalContinuityDialogBase", "5 - Friction"))
        self.costRun.setText(_translate("EcologicalContinuityDialogBase", "Lancer la modélisation"))
        self.costStartRasterLabel.setText(_translate("EcologicalContinuityDialogBase", "2 - Vecteur de départ"))
        self.costPermRasterLabel.setText(_translate("EcologicalContinuityDialogBase", "3 - Raster de friction"))
        self.costMaxCost.setText(_translate("EcologicalContinuityDialogBase", "4 - Coût max"))
        self.costAdd.setText(_translate("EcologicalContinuityDialogBase", "Ajouter dispersion"))
        self.costSTLabel.setText(_translate("EcologicalContinuityDialogBase", "1 - Sous-trame"))
        self.costStartRasterLabel_2.setText(_translate("EcologicalContinuityDialogBase", "Sélectionner couche"))
        self.costStartRasterLabel_3.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir couche"))
        self.costStartRasterLabel_4.setText(_translate("EcologicalContinuityDialogBase", "Sélectionner couche"))
        self.costStartRasterLabel_5.setText(_translate("EcologicalContinuityDialogBase", "Ouvrir couche"))
        self.label_28.setText(_translate("EcologicalContinuityDialogBase", "Dispersion"))
        self.costRemove.setText(_translate("EcologicalContinuityDialogBase", "Supprimer"))
        self.pluginTabs.setTabText(self.pluginTabs.indexOf(self.tab), _translate("EcologicalContinuityDialogBase", "6 - Dispersion"))

from qgsfieldcombobox import QgsFieldComboBox
from qgsfieldexpressionwidget import QgsFieldExpressionWidget
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
from qgsspinbox import QgsSpinBox
